### ISSUE TITLE
How to program WindowCovering shutters whit TargetPosition DPT1

### ISSUE THREAD

**Issue by bbdj-dev** [snowdd1/homebridge-knx#102]
Hi,
in my device can't set the position but only the opening / closing and then stop it:

Long  3/0/7 (0-Close 1-Open)
Short  3/1/7 (1-Stop)
Position (only read) 3/3/7 (0..100)

I've try to do this configuration:

{
    "ServiceType": "WindowCovering",
    "Handler": "GiraJalousieActuator",
    "ServiceName": "Tapparella finestra sala",
    "Characteristics": [
        {
            "Type": "CurrentPosition",
            "Listen": ["3/3/7"],
            "DPT": "DPT5.001"
        },
        {
            "Type": "TargetPosition",
            "Set": ["3/0/7"],
            "DPT": "DPT1"
        },
        {
            "Type": "PositionState"
        }
    ],
    "KNXReadRequests": ["3/0/7"],
    "LocalConstants": {
        "TimeOutSecs": 20
    }
}

but don't work, can you help me?

Thanks,
Gianluca

**Comment by hyperbart** [comment]
Ciao Gianluca

I think you made some mistakes there. I don't have a GIRA but an MDT JAL. Comparable. I think you should get it to work basically and then add the stop-functionality. Normally you shouldn't change/transform the DPT types.

Can you post a screenshot of the GA's assigned to the channels on your GIRA?

This is my config:

3/1/3R = Channel 32 in ETS on MDT JAL, This is a STATUS object (=READ), current percentage reported by MDT JAL
3/0/3R = Channel 30 in ETS on MDT JAL, This is a SET object (=WRITE percentage to set height)
3/3/3R = Channel 27 in ETS on MDT JAL, This is a STATUS object (=READ)

`
                {
                    "ServiceType": "WindowCovering",
                    "ServiceName": "Screen",
                    "Characteristics": [
                        {
                            "Type": "CurrentPosition",
                            "Listen": [
                                "3/1/3R"
                            ]
                        },
                        {
                            "Type": "TargetPosition",
                            "Set": [
                                "3/0/3R"
                            ]
                        },
                        {
                            "Type": "PositionState",
                            "Listen": [
                                "3/3/3R"
                            ]
                        }
                    ]
                },
`

**Comment by bbdj-dev** [comment]
Ciao hyperbart,
I dn’t have GIRA me too, I’ve copyed from example... I’ve siemens but don’t work anymore so I implemented that logic on EVEServer  (suite software for supervision) with virtual adress:

"DeviceName": "Tapparella finestra sala",
"Services": [{
    "ServiceType": "WindowCovering",
    "ServiceName": "Tapparella finestra sala",
    "Characteristics": [{
        "Type": "TargetPosition",
        "Set": ["13/5/0"],
        "Listen": ["3/3/7"]
      },{
        "Type": "CurrentPosition",
        "Listen": ["3/3/7"]
      },{
        "Type": "PositionState"
      }],
    "KNXReadRequests": ["3/3/7"]
}]

Thanks

**Comment by HolyGiraffe** [comment]
is it working now?
i just finished setting up mine, maybe i can support you

**Comment by bbdj-dev** [comment]
In Siemens the TargetPosition (DPT5) is only read, the shutter move only with 1 or 0 so how send DPT1 in WindowCovering for open o close the shutter?

Thanks so much.

Gianluca

 

 

Da: HolyGiraffe [mailto:notifications@github.com] 
Inviato: mercoledì 4 ottobre 2017 21:46
A: snowdd1/homebridge-knx <homebridge-knx@noreply.github.com>
Cc: Gianluca <bbdj74@gmail.com>; State change <state_change@noreply.github.com>
Oggetto: Re: [snowdd1/homebridge-knx] How to program WindowCovering shutters whit TargetPosition DPT1 (#102)

 

is it working now?
i just finished setting up mine, maybe i can support you

**Comment by bbdj-dev** [comment]
In Siemens the TargetPosition (DPT5) is only read, the shutter move only with 1 or 0 so how send DPT1 in WindowCovering for open o close the shutter?
Thanks so much.
Gianluca
