### ISSUE TITLE
Help with shutters control

### ISSUE THREAD

**Issue by cgalliani** [snowdd1/homebridge-knx#109]
I am trying to get simple shutters working in homebridge-knx with limited success. 
I am new with homebridge. So far I could get on/off lights working  fine with my configuration.
My shutters are roller shutters with no slats. I just need to move them up and down. 
My controls are ABB JRA/S. 
I have the following GA's:
// for operations with push-buttons
  2/4/0: up/down control, 
  2/4/1: stop
// added for homebridge-knx operations
2/4/6: move to (height 0..255)
2/4/7: current position (height status 0..255)
I checked that the latter GA's works ok by writing and reading with ETS.
I have little understanding of the necessary JSON data. Hence, copying some examples, I ended up with this:
...
            "DeviceName": "Studio Shutters",
            "Services": [
                {
                    "ServiceType": "WindowCovering",
                    "ServiceName": "Shutters",
                    "TargetPosition": {
                        "Set": "2/4/6R"  // tried with or without R
                    },
                    "CurrentPosition": {
                        "Listen": "2/4/7R"
                    },
                    "DPT": "DPT5"   // tried with or without this
                 }
            ]
         }
 
The shutters do not move. I don't see any communication trace in the KNXD log, all options on. 
For teh time being, I am running homebridge-knx on MacOS 10 with knxd on a RASPI.
Any help will be very appreciated.
Regards.
Carlo

**Comment by snowdd1** [comment]
Please have a look into the add-ins (aka Handlers) that convert between native HomeKit types and existing KNX physical devices.

**Comment by cgalliani** [comment]
Thanks Raoul.

It looks my ABB JRA/S. shutter actuators work well enough without a specific handler.

However I had to use a proper device record and enable the correct feedback objects in ETS.
I guess the first sample I used was outdated.

Below is the actual json record.
Greetings.
Carlo

{
  "DeviceName": "Living Shutters",
  "Services": [
    {
      "ServiceType": "WindowCovering",
      "ServiceName": "Living Shutters",
      "Characteristics": [
        {
          "Type": "TargetPosition",
          "Set": [
            "2/3/23"
          ],
          "Reverse": true
        },
        {
          "Type": "CurrentPosition",
          "Listen": [
            "2/3/30"
          ],
          "Reverse": true
        }
      ]
    }
  ]
}
