### ISSUE TITLE
Failed to update

### ISSUE THREAD

**Issue by migabc** [snowdd1/homebridge-knx#110]
Hi,
When trying to update I get this error:
Any idea what's wrong?

pi@raspberrypi:~ $ date; sudo npm update -g homebridge-knx
Mon Dec  4 01:04:54 WET 2017
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/snowdd1/homebridge-knx.git /root/.npm/_cacache/tmp/git-clone-08028368
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-08028368': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-04T01_05_09_863Z-debug.log

**Comment by snowdd1** [comment]
I think `-g` requires `--unsave-perm` or something to be able to write things as root, doesn't it?

**Comment by migabc** [comment]
Still getting the same error:

pi@raspberrypi:~ $ date; sudo npm update -g --unsafe-perm homebridge-knx 
Fri Dec 29 14:13:16 WET 2017
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q git://github.com/snowdd1/homebridge-knx.git /root/.npm/_cacache/tmp/git-clone-d2fcea4f
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-d2fcea4f': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-29T14_13_32_504Z-debug.log
pi@raspberrypi:~ $

**Comment by snowdd1** [comment]
Sorry, this might have to do with your local installation.

**Comment by migabc** [comment]
I re-installed and now it's updated:


pi@raspberrypi:~ $ sudo npm install -g --unsafe-perm homebridge
/usr/bin/homebridge -> /usr/lib/node_modules/homebridge/bin/homebridge
. . .
+ homebridge@0.4.33
added 17 packages and updated 2 packages in 195.145s
pi@raspberrypi:~ $

**Comment by migabc** [comment]
btw, do you know when will the Sprinker service be available?

**Comment by snowdd1** [comment]
The services depend on the homebridge/hap-nodejs installation only. If they have included it into the base work, you can immediatly use it in homebridge-knx (searches for the key word in the list of existing services). homebridge-knx does not bring any own interpretations of services of characteristics, besides the *handler*s that do something with the data between homebridge and knx.

**Comment by migabc** [comment]
KhaosT commented on 2018-01-15
Not yet, I'll try to add those soon.
--
