### ISSUE TITLE
Sprinkler and Faucet support (iOS 11)

### ISSUE THREAD

**Issue by migabc** [snowdd1/homebridge-knx#111]
Does homebridge already support Sprinkers and Faucets?

Does anybody know what are the new Service and Characteristic UUIDs for these new HomeKit accessories?

P.S. Currently my KNX garden sprinkers are configured on knx_config.json as normal Homekit switches and I would like to change the configuration to Sprinkers.

Thanks.

**Comment by snowdd1** [comment]
I've just checked the source https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js for "faucet" and "sprinkler" and there is nothing in it, yet.

**Comment by justinfanok** [comment]
Characteristic.ValveType.UUID = '000000D5-0000-1000-8000-0026BB765291';

// The value property of ValveType must be one of the following:
Characteristic.ValveType.GENERIC_VALVE = 0;
Characteristic.ValveType.IRRIGATION = 1;
Characteristic.ValveType.SHOWER_HEAD = 2;
Characteristic.ValveType.WATER_FAUCET = 3;

/**
 * Characteristic "Version"


It looks like it is now
