### ISSUE TITLE
Doorbell

### ISSUE THREAD

**Issue by migabc** [snowdd1/homebridge-knx#113]
Hi,

How can I implement a doorbell?
I'm trying like this but it does not seem to work:

                    "ServiceType": "Doorbell",
                    "ServiceName": "Front Doorbell",
                    "Characteristics": [
                        {
                            "Type": "ProgrammableSwitchEvent",
                            "Listen": [
                                "2/1/12"
                            ],
                            "DPT": "DPT5"
                        }
                    ]

Any help is appreciated
P.S. My doorbell is currently working as a Service ContactSensor but I would like to change it to Service DoorBell

**Comment by snowdd1** [comment]
Hi @migabc ,
that topic is discussed [here](https://github.com/snowdd1/homebridge-knx/issues/84) in #84  
I am not proficient in that, not having a comparable device.
BR
