### ISSUE TITLE
Dimmers not working

### ISSUE THREAD

**Issue by deejonz** [snowdd1/homebridge-knx#114]
Hello, 

since I upgraded to 0.3.0 version the dimmers are not working anymore. Moving the slider the light intensity changes but not regularly but changes with random values. I tried to upgrade now also node and homebridge with the same result.

**Comment by hyperbart** [comment]
Might be related to:
https://github.com/snowdd1/homebridge-knx/issues/47

**Comment by snowdd1** [comment]
Is.
