### ISSUE TITLE
How can I configure a OR condition for the Listen statement

### ISSUE THREAD

**Issue by migabc** [snowdd1/homebridge-knx#124]
Hi,

I need to configure a ContactSensor that will OPEN when any GA is triggered 
How can I configure a OR condition for the Listen statement?
I.e, I need to to Listen for one OR another GA (not AND)

OPEN the contact sensor if 8/0/12 OR 8/0/22 are triggered

`                {
                    "ServiceType": "ContactSensor",
                    "ServiceName": "All Doors & Windows",
                    "Characteristics": [
                        {
                            "Type": "ContactSensorState",
                            "Listen": [
                                "8/0/12",      >>>> All basement Doors & Windows
                                "8/0/22"      >>>> All mainfloor Doors & Windows
                            ]
                        }
                    ]
                }
`

**Comment by migabc** [comment]
That's what I did (see code above) but it doesn't seem to work consistently
Sometimes when either one is open (8/0/12 OR 8/0/22) but the resulting ContactSensor does not reflect that

**Comment by wendelit** [comment]
Try this:
"Characteristics": [
                        {
                            "Type": "ContactSensorState",
                            "Handler": "ContactSensor",
                            "Listen": [
                                "8/0/12",
                                "8/0/13"
                            ]
                        }
                    ],
                    "KNXReadRequests": [
                        "8/0/12",
                        "8/0/13"
                    ]

**Comment by snowdd1** [comment]
@wendelit is right - negative telegrams overwrite positive telegrams in that setup.  
Basically it's neither *OR* nor *AND* it's just *later supersedes earlier* telegrams.  

So, if you get one ON telegram and an OFF later from the other address, the contact will show OFF in homekit.


For a real AND or OR circuit you need to write an handler or use some backend software like a home server or node-red.
