### ISSUE TITLE
GarageDoorOpenerAdvanced.js

### ISSUE THREAD

**Issue by c-o-m-m-a-n-d-e-r** [snowdd1/homebridge-knx#138]
Hey,
in the GarageDoorOpenerAdvanced.js File in Line 464 ... i think it must be

`if (field === "KNXDoorClose") {`

or not ?

**Comment by giase82** [comment]
Hi,

I don't think so... The field in the example below is:
`
                        {
                            "Type": "KNXDoorClosed",
                            "Listen": "2/3/2",
                            "DPT": "DPT1"
                        },`

Do I missunderstand your question?

//Christof

**Comment by giase82** [comment]
However, I agree this is inconsistent with KNXDoorOpen. One could fix it the one or the other way around.

**Comment by c-o-m-m-a-n-d-e-r** [comment]
I know this was in the Example ... but i was debugging the process an the Type "KNXDoorClosed" was never get called. 

After changing the Type to "KNXDoorClose" without the "d" and changing Line 464 everything was working fine.

**Comment by giase82** [comment]
Sorry for that. Fixed it. Struggling with the git-magic right now for creating branches, commit etc

**Comment by snowdd1** [comment]
Hi @giase82 ,  I think @c-o-m-m-a-n-d-e-r  Paul already fixed that in PR https://github.com/snowdd1/homebridge-knx/pull/158
Right?

**Comment by giase82** [comment]
Yes! Sorry I did forget ;)

**Comment by snowdd1** [comment]
closed with #158
