### ISSUE TITLE
ServiceType Doorbell

### ISSUE THREAD

**Issue by migabc** [snowdd1/homebridge-knx#143]
Hi,

I'm trying to add a Doorbell but I'm getting a "Not supported" icon on the Home app

`                    "ServiceType": "Doorbell",
                    "ServiceName": "Front Doorbell",
                    "Characteristics": [
                        {
                            "Type": "ProgrammableSwitchEvent",
                            "Set": [
                                "0/0/3"
                            ],
                            "DPT": "DPT1",
                            "Listen": [
                                "0/0/3"
                            ]
                        }
                    ],
`
Isn't this service supposed to be supported already?
I'm running iOS 12.1.4

P.S. Checked other similar posts/issues but they have all been closed

https://github.com/snowdd1/homebridge-knx/issues/113
https://github.com/snowdd1/homebridge-knx/issues/84

Any help is appreciated
P.S. My doorbell is currently working as a Service ContactSensor but I would like to change it to Service DoorBell

The Home app Doorbell Icon is supposed to look like this:
[https://i.redd.it/jzj91536t4401.jpg](url)

**Comment by snowdd1** [comment]
I tried the doorbell service in iOS 13 and it results in a push notification - it still says in home app that it unsupported though.
