### ISSUE TITLE
Different sets of devices not responding

### ISSUE THREAD

**Issue by hyperbart** [snowdd1/homebridge-knx#144]
A while ago I "updated" my Homebridge and KNX setup, hoping to fix the issue with the brightness and dimming (which wasn't solved but that's another story ;)

Everything seemed okay, but after a while I started noticing that subsets of my devices transitioned to a "no response" state. There is no pattern. After a restart everything is reachable again.

The first time I noticed the problem it was a set of outlets which were not responding. All of the outlets are on the same MDT actor. It's not bound to a room or a defintion of a Device. With the outlets for example one outlet in the bedroom was okay while te other one was unreachable.
Yesterday and today it's a set of light bulbs.

Coincidental these errors pop up and correspond to the time I noticed the errors (+1h, time is 1h off)

Feb 16 22:30:42 homekit homebridge[7199]: [2/16/2019, 10:30:42 PM] [homebridge-knx.KNX] [ERROR] knxwrite:openTGroup: Error: request invalid
Feb 16 22:30:42 homekit homebridge[7199]: [2/16/2019, 10:30:42 PM] [homebridge-knx.KNX] [ERROR] knxwrite:openTGroup: Error: request invalid
Feb 16 22:30:42 homekit homebridge[7199]: [2/16/2019, 10:30:42 PM] [homebridge-knx.KNX] [ERROR] knxwrite:openTGroup: Error: request invalid
Feb 16 22:30:42 homekit homebridge[7199]: [2/16/2019, 10:30:42 PM] [homebridge-knx.KNX] [ERROR] knxwrite:openTGroup: Error: request invalid
Feb 16 22:30:42 homekit homebridge[7199]: [2/16/2019, 10:30:42 PM] [homebridge-knx.KNX] [ERROR] knxwrite:openTGroup: Error: request invalid
Feb 16 22:30:42 homekit homebridge[7199]: [2/16/2019, 10:30:42 PM] [homebridge-knx.KNX] [ERROR] knxwrite:openTGroup: Error: request invalid
Feb 16 22:30:42 homekit homebridge[7199]: [2/16/2019, 10:30:42 PM] [homebridge-knx.KNX] [ERROR] knxwrite:openTGroup: Error: request invalid
Feb 16 22:30:42 homekit homebridge[7199]: [2/16/2019, 10:30:42 PM] [homebridge-knx.KNX] [ERROR] knxwrite:openTGroup: Error: request invalid
Feb 16 22:30:42 homekit homebridge[7199]: [2/16/2019, 10:30:42 PM] [homebridge-knx.KNX] [ERROR] knxwrite:openTGroup: Error: request invalid

**Comment by coinraiser** [comment]
Try looking here https://github.com/snowdd1/homebridge-knx/issues/99

**Comment by snowdd1** [comment]
Duplicate to #99, closing
