### ISSUE TITLE
Solution for brightness setting also turns device on?

### ISSUE THREAD

**Issue by zork17** [snowdd1/homebridge-knx#145]
My dimmer lights could not be used with HomeKit since whenever I set the brightness, the lights are set ON with full 100% brightness.
I found several mentions of this issue, but I couldn't find a solution.
Is there a solution or workaround for this problem?

**Comment by coinraiser** [comment]
Im on mobile now but can send u the one that is working for me

**Comment by zork17** [comment]
@coinraiser 
> Im on mobile now but can send u the one that is working for me

Thanks, looking forward to this.
Does it involve changing the code of some plugin?

**Comment by coinraiser** [comment]
{
            "DeviceName": "Light",
            "Services": [
                {
                    "ServiceType": "Lightbulb",
                    "ServiceName": "Light",
                    "Characteristics": [
                        {
                            "Type": "On",
                            "Set": [
                                "4/1/7"
                            ],
                            "Listen": [
                                "4/1/8"
                            ],
                            "DPT": "DPT1"
                        },
                        {
                            "Type": "Brightness",
                            "Set": [
                                "4/1/10"
                            ],
                            "Listen": [
                                "4/1/11"
                            ],
                            "DPT": "DPT5.001"
                        }
                    ],
                    "subtype": "SUB_ce098157-b7eb-4406-9541-f8470b8101a0"
                }
            ],
            "UUID": "7fef2a1a-65c4-4530-a022-49b1cb81cccd"
        }

**Comment by zork17** [comment]
Basically I have the same settings except for this line in the Brightness:
"DPT": "DPT5.001"

What is the change that you made to fix this problem?

**Comment by coinraiser** [comment]
I m using addin from /usr/lib/node_modules/homebridge-knx/lib/addins

**Comment by zork17** [comment]
what does it mean?
Do you use a specific addin?
I do not know which addin I use. As I said, I have the same syntax in the knx config file and I don't know which addin is used

**Comment by coinraiser** [comment]
Try this one m8
[LIGHT.zip](https://github.com/snowdd1/homebridge-knx/files/2884232/LIGHT.zip)
if it dont work for u then use the one from addin folder,that one is defined by "Handler": "Dimmer"
[Dimmer.zip](https://github.com/snowdd1/homebridge-knx/files/2884253/Dimmer.zip)

**Comment by zork17** [comment]
1) the syntax in LIGHT.zip looks like the one I have with ServiceType Lightbulb. What is the difference?
2) In Dimmer.zip there is indeed a new Handler and extra parameters at the end. How do I use a Handler? Should I just add its line in the config file?

**Comment by coinraiser** [comment]
copy the whole lines from dimmer.zip file,change GA and parameters on bottom.
u can check addin config and what it does in /usr/lib/node_modules/homebridge-knx/lib/addins.

**Comment by zork17** [comment]
I set it up as you describe but still, the dimming does not work properly.
Any other suggestions?

**Comment by coinraiser** [comment]
What problem r u experiencing?do u have read flags on knx side for status adresses?

**Comment by zork17** [comment]
The problem is I can't set Brightness or dim the lights. They are set to 100%.
If I set the brightness using another app (not HomeKit) than Homekit displays the correct dimming. 
So read works but not write.

I don't know what is read flags on knx side for status addresses?

**Comment by coinraiser** [comment]
Template works for me just fine.Are u sure u not using relative 4 bit dimming for brightness?U need 1byte absolute brightness value to get it to work.

**Comment by zork17** [comment]
I had a little error in the config file.
It now works great with the Dimmer handler.
Thanks a lot for the help!

**Comment by coinraiser** [comment]
Glad i could help
