### ISSUE TITLE
Syntax Error - Homebridge does not start anymore

### ISSUE THREAD

**Issue by giase82** [snowdd1/homebridge-knx#146]
Hi,

Since an updated today, I get the following syntax-error during startup. Does anybody have an idea?

Feb 20 19:57:24 shpi2 homebridge[21502]: /usr/local/lib/node_modules/homebridge-knx/node_modules/debug/src/node.js:132
Feb 20 19:57:24 shpi2 homebridge[21502]:         let val = process.env[key];
Feb 20 19:57:24 shpi2 homebridge[21502]:         ^^^
Feb 20 19:57:24 shpi2 homebridge[21502]: SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
Feb 20 19:57:24 shpi2 homebridge[21502]:     at exports.runInThisContext (vm.js:53:16)
Feb 20 19:57:24 shpi2 homebridge[21502]:     at Module._compile (module.js:373:25)
Feb 20 19:57:24 shpi2 homebridge[21502]:     at Object.Module._extensions..js (module.js:416:10)
Feb 20 19:57:24 shpi2 homebridge[21502]:     at Module.load (module.js:343:32)
Feb 20 19:57:24 shpi2 homebridge[21502]:     at Function.Module._load (module.js:300:12)
Feb 20 19:57:24 shpi2 homebridge[21502]:     at Module.require (module.js:353:17)
Feb 20 19:57:24 shpi2 homebridge[21502]:     at require (internal/module.js:12:17)
Feb 20 19:57:24 shpi2 homebridge[21502]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-knx/node_modules/debug/src/index.js:9:19
Feb 20 19:57:24 shpi2 homebridge[21502]:     at Module._compile (module.js:409:26)
Feb 20 19:57:24 shpi2 homebridge[21502]:     at Object.Module._extensions..js (module.js:416:10)
Feb 20 19:57:24 shpi2 homebridge[21502]:     at Module.load (module.js:343:32)
Feb 20 19:57:24 shpi2 homebridge[21502]:     at Function.Module._load (module.js:300:12)
Feb 20 19:57:24 shpi2 homebridge[21502]:     at Module.require (module.js:353:17)
Feb 20 19:57:24 shpi2 homebridge[21502]:     at require (internal/module.js:12:17)
Feb 20 19:57:24 shpi2 homebridge[21502]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-knx/lib/customtypes/knxthermostat.js:8:1
Feb 20 19:57:24 shpi2 homebridge[21502]:     at Module._compile (module.js:409:26)

**Comment by coinraiser** [comment]
Did u update homebridge or knxd?

**Comment by giase82** [comment]
homebridge-knx and homebridge using npm update

**Comment by coinraiser** [comment]
But did u update knxd?

**Comment by coinraiser** [comment]
Whay version of knxd and homebridge are u running?

**Comment by coinraiser** [comment]
I have created discod server for homebridge-knx and knx general talk if someone is interested.
https://discord.gg/VbVuGKB

**Comment by giase82** [comment]
Sorry, closing this right away. Had a too old version of node running and had to re-compile.

Cheers!
