### ISSUE TITLE
New Addins StatelessSwitchKnx

### ISSUE THREAD

**Issue by kakaki** [snowdd1/homebridge-knx#150]
I have created a simple addin to control homekit devices from knx buttons (like tritton) - this gives option to assign one, two or three clicks (aka long press in homekit) to physical button and add actions or scenes to it in homekit.

Put file in lib/addins/StatelessSwitchKnx.js

[StatelessSwitchKnx.js.zip](https://github.com/snowdd1/homebridge-knx/files/3304374/StatelessSwitchKnx.js.zip)

**Comment by snowdd1** [comment]
I'll put that into the next version!
Thank you for sharing!
