### ISSUE TITLE
Simultaneous sending of commands

### ISSUE THREAD

**Issue by TilBlechschmidt** [snowdd1/homebridge-knx#156]
When sending commands in quick succession some of them either don’t get through to the KNX or overlap and thus some commands are not being executed. This is especially prevailing when triggering scenes with a multitude of devices. It would be nice to have a global setting for a minimum delay between commands sent out to the KNX tunnel and thus an output queue.

I am not sure whether or not this is a transmission issue between `homebridge-knx` and `knxd` or if `knxd` does some weird stuff on its side or the data gets through onto the bus but just collides there. But it would definitely be fixable within this plugin and seems to be the easiest way.

**Comment by snowdd1** [comment]
look at the knxd docu, there are options to limit the speed knxd tries to send out telegrams to the router/bus/hardware.
