### ISSUE TITLE
How to add an Outlet

### ISSUE THREAD

**Issue by gjniewenhuijse** [snowdd1/homebridge-knx#16]
I like to add a switching outlet for my Fountain, So i can set my fountain on/off and get the current state of the fountain.

But then i receive: [KNX] [ERROR] unknown 'type' property of [Outlet] for service [Test] in config.json. 
```
{
                    "accessory_type": "knxdevice",
                    "description": "Only generic type knxdevice is supported, all previous knx types have been merged into that.",
                    "name": "Test",
                    "services": [
                        {
                            "type": "Outlet",
                            "description": "iOS8 Lightbulb type, supports On (Switch) and Brightness",
                            "name": "Test",
                            "On": {
                                "Set": "9/1/9"
                            },
							"OutletInUse": {
                                "Listen": ["9/2/9"]
                            }
                        }
                    ],
                    "services-description": "Services is an array, you CAN have multiple service types in one accessory, though it is not fully supported in many iOS HK apps, such as EVE and myTouchHome"
                },
```

**Comment by petkoe** [comment]
Hello, 

i have use switch and get the feedback via listen in "On". 

              {
                    "name": "Steckdose SüdWest Ecke",
                    "services": [
                        {
                            "type": "Switch",
                            "name": "Steckdose SüdWest Ecke",
                            "On": {
                                "Set": "1/5/25",
                                "Listen": [
                                    "1/5/27"
                                ]
                            }
                        }
                    ]
                },
The Construct "OutletIUse" is for an outlet which knows wether it is used or not. The Listen in On is just to know wether it is on or not. Thats what Raoul told me. Hope this helps.

**Comment by snowdd1** [comment]
@petkoe is right. Frankly I didn't test the outlet service, as I have no outlets with "in use" sensors - and all others are simply switches (for power).

**Comment by snowdd1** [comment]
I have added the missing outlet line. New version is 0.2.5. If anyone would care to test that then I will push it to npm.

**Comment by gjniewenhuijse** [comment]
It looks like it works, no errors at startup. 
But with Insteon+ i see only the device, no control items, maybe the outlet device is not supported by insteon?

**Comment by snowdd1** [comment]
Have you tried Eve instead? It's free.
