### ISSUE TITLE
Issues with npm-knx

### ISSUE THREAD

**Issue by Luehrsen** [snowdd1/homebridge-knx#162]
Now this one was hard to figure out. 😄 

On the current master branch and due to the excellent work by Paul, the existing implementations based on knxd WILL break. Existing users will have to update the knx_config.json and add "knxd: true" to the root of the json. 

This might lead to increased support issues. You might want to leave the default case as is and make the new way the optin way. 

I noticed that because the communication from knx to hk broke. No messages from the bus arrived in homebridge-knx. The other way around was fine. Means: I was able to switch lights from HK, but when I switched lights in KNX, the updated state was not reflected in HK.

**Comment by snowdd1** [comment]
You are right. Will change that to force "knxd": false

**Comment by snowdd1** [comment]
fixed with https://github.com/snowdd1/homebridge-knx/commit/daec87f9d60a72f4aef414afd771011850e613f3

**Comment by snowdd1** [comment]
... in version 0.3.24 in npm.
