### ISSUE TITLE
KNXNetHeader error

### ISSUE THREAD

**Issue by StofLE** [snowdd1/homebridge-knx#164]
Since update to homebridge-knx v0.3.24 and homebridge v1.0.4 I got:
...
[warn] 2020-05-02 23:00:35.523 read KNXNetHeader: unhandled serviceType = undefined,
[warn] 2020-05-02 23:00:35.522 read KNXNetHeader: unhandled serviceType = undefined,
[warn] 2020-05-02 23:07:52.875 read KNXNetHeader: unhandled serviceType = undefined,
[warn] 2020-05-02 23:07:58.718 read KNXNetHeader: unhandled serviceType = undefined
....

In config.json I added {"name":"KNX", "platform":"KNX"}. No else changes but "knxdconnection": "knxd", in knx_config.json.

Update:
I downgraded to homebridge-knx v0.3.21 (keeping homebridge at v1.0.4) and everything is fine. Btw...I got the error on v0.3.24 always (knxdconnection set to "knxd" or "knxjs"). Also with an empty knx_config (no devices).

Stefan

**Comment by snowdd1** [comment]
I think I found it. There was a missing change for the changed knxconnection setting.
Will publish version 0.3.26 soon.
