### ISSUE TITLE
TypeError: Cannot convert object to primitive value at KNXPlatform.

### ISSUE THREAD

**Issue by CyberChris79** [snowdd1/homebridge-knx#168]
Hallo,

als ich versucht hatte per Browser auf den KNX Server zuzugreifen z.B. http://192.168.178.210:18081/availcharacteristics, erhielt ich folgende Fehlermeldung auf der Homebridge und diese wurde dann auch mit einem Got SIGTERM, shutting down Homebridge beendert.

Die ganze Fehlermeldung lautet:
TypeError: Cannot convert object to primitive value at KNXPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-knx/index.js432:34
at Server.emit (events.js:188:13)
at parserOnIncoming (_http_server.js:676:12)
at HTTPParser.parserOnHeadersComplete
(_http_common.js:113:17)
Got SIGTERM, shutting down Homebridge...

**Comment by snowdd1** [comment]
Hi welche node version? Bei mir geht es nämlich noch!

**Comment by snowdd1** [comment]
And please, post in English here, if you want to post in German please do so at https://github.com/snowdd1/homebridge-knx-de

**Comment by CyberChris79** [comment]
Hallo Raoul,

 

vielen Dank für deine Rückmeldung.

 

Ich habe zurzeit die 11.6.0 installiert.

Auch die JQuery Version habe ich upgedatet.

 

Viele Grüße

Christian

 

 

Von: Raoul <notifications@github.com> 
Gesendet: Freitag, 22. Mai 2020 15:06
An: snowdd1/homebridge-knx <homebridge-knx@noreply.github.com>
Cc: CyberChris79 <cyberchris79@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [snowdd1/homebridge-knx] TypeError: Cannot convert object to primitive value at KNXPlatform. (#168)

 

Hi welche node version? Bei mir geht es nämlich noch!

**Comment by snowdd1** [comment]
Versuche mal node v12.
jQuery nutze ich nicht in meinem Code.
Hast Du die letzte homebridge & homebridge-knx (0.3.25)?

**Comment by CyberChris79** [comment]
Guten Morgen Raoul,

ich habe nun auch die NodeJS auf die 12.16.3 upgedated. 
Die Homebrige und Homebrige-Knx waren schon auf dem neusten Stand. 
Leider kommt die Fehlermeldung erneut. 

Bringt es was wenn ich die Homebridge-knx deinstallieren und neu installiere?



Grüße
Christian

**Comment by snowdd1** [comment]
Hallo Christian, 
keine Ahnung - ich weiß ja nicht woran es liegt. Alles neu zu installieren - vielleicht auf einem anderen Gerät (oder anderen Verzeichnis, je nach setup) könnte helfen um herauszufinden ob es an der Installation liegt.
Ich habe mir die Codezeile mal angesehen, da wird aus Elemente aus HAP-nodeJS zugegriffen, ich gucke mal ob die in der Quelle was verändert haben.

**Comment by snowdd1** [comment]
Ok, I have set up a dev environment w/latest homebridge and are seeing this crash sporadically.

**Comment by CyberChris79** [comment]
Hallo Raoul,

vielen Dank. 
Jetzt funktioniert es wieder. 

Grüße 
Christian
