### ISSUE TITLE
Need to put initial config in config.json again?

### ISSUE THREAD

**Issue by HolyGiraffe** [snowdd1/homebridge-knx#174]
Good day all, 

i recently had a issue getting homebridge-knx up and running again. 
The plugin was loading according to the homebridge log, but was not connecting to knxd.

Fix was to put the platform config from knx_config.json in config.json.
Maybe this helps other users, or my installation was broken somehow.
I can provide more information if needed.

greetings, Giraffe

**Comment by snowdd1** [comment]
Please see #163 and the [Changelog for v0.3.23](https://github.com/snowdd1/homebridge-knx/blob/master/CHANGELOG.md#0323)
