### ISSUE TITLE
Enable and use debug output homebridge.log

### ISSUE THREAD

**Issue by DronNick** [snowdd1/homebridge-knx#176]
I'm trying to implement a handler for a KNX tubing motor and need some debug output.

In the Gira Actuator Handler i can see following line:
`log('INFO: onKNXValueChange(' + field + ", "+ oldValue + ", "+ knxValue+ ")");`

But i never see the output of this in the homebridge.log.

How can i activate the debuf and info logging, so the output is visible in the homebridge.log?

**Comment by snowdd1** [comment]
How do you start homebridge?

**Comment by DronNick** [comment]
Thank you for pointing out. It is a docker container provided here https://registry.hub.docker.com/r/oznu/homebridge/ that uses /etc/services.d/.homebridge/run as a start script.

I had to set environment varibale of the doker container HOMEBRIDGE_DEBUG to 1 in order to run homebridge in debug mode.
