### ISSUE TITLE
TemperatureSensor give me only 0.0°

### ISSUE THREAD

**Issue by marcobastianon** [snowdd1/homebridge-knx#177]
hi all, i'm tryng to create a TemperatureSensor using this code:

    {
      "DeviceName": "TempStudio",
      "Services": [{
          "ServiceType": "TemperatureSensor",
          "ServiceName": "TempStudio",
          "Characteristics": [{
              "Type": "CurrentTemperature",
              "Listen": ["4/6/6"]
            }
          ]
        }
      ]
    }

the thermostat tells me that the temperature is 0.0 ° C and I can't understand where my mistake is.
I have the error with both iOS 13 and iOS 14.

in the knx bus @ 4/6/6 i've 24.2 ° C

**Comment by marcobastianon** [comment]
some one have temperature working on "TemperatureSensor" or "Thermostat"??

**Comment by snowdd1** [comment]
Sure I have, multiple of them:
```json
                {
                    "ServiceType": "TemperatureSensor",
                    "ServiceName": "Esszimmer Temperatur",
                    "Characteristics": [
                        {
                            "Type": "CurrentTemperature",
                            "Listen": [
                                "3/1/41"
                            ],
                            "MaxValue": 60,
                            "MinValue": -20
                        }
                    ],
                    "KNXReadRequests": [
                        "3/1/41"
                    ]
                }
```
with `3/1/41` being a 2-byte float from my [Berker B.IQ](https://www.hager.de/knx-gebaeudesystemtechnik/knx-ets/bediensysteme-b.iq/75663599/37594.htm) room temp sensor.

**Comment by marcobastianon** [comment]
can you help me understending why u add:
"KNXReadRequests": [
   "3/1/41"
]

**Comment by snowdd1** [comment]
Sure , it makes homebridge-knx issue a read request at startup, so you don’t need to wait too long to get the value filled. 

More important are the min and max settings because the values might otherwise be ignored.

**Comment by marcobastianon** [comment]
@snowdd1 in you opinion:
![image](https://user-images.githubusercontent.com/23148549/92149456-56264680-ee1e-11ea-86e3-683e4f1ca595.png)
if i recive this telegram.. homebridge-knx might not interpret it correctly?... in all my test on ets i recive a telegram like this, but on homebridge nothing change..

**Comment by snowdd1** [comment]
You might want to start homebridge in debug mode and post the log here.

**Comment by marcobastianon** [comment]
DEBUG=* homebridge &> file.ext

i've a long file, but nothing on temperature, m'i wrong?

**Comment by marcobastianon** [comment]
i realy can not find a solution.. i see on ets room temp change, but on homekit nothing change..

**Comment by marcobastianon** [comment]
i can’t understand why all my telegram on with temperature are completely ignored.. con some one help me to find a solution? because i can not use thermostat.

**Comment by marcobastianon** [comment]
what version of knxd are you using? it seems that my installed version is not compatible with dtp9 .. using "knxtool vbusmonitor1 ip: localhost" I can't see any telegram concerning the temperature, I only see telegrams for switching on lights.
