### ISSUE TITLE
homebridge-knx does not work with latest homebridge@1.1.6

### ISSUE THREAD

**Issue by migabc** [snowdd1/homebridge-knx#182]
Hi,

I upgraded homebridge to the lastest version (1.1.6) and now homebridge-knx does not load my knx accessories :-(
Log just shows this:

Nov  2 14:16:42 raspberrypi homebridge[3535]: [info] "2020-11-02T14:16:42.989Z"  'Loading knx: KNXnet/IP protocol implementation for Node(>=4.x), version: 2.3.8'
Nov  2 14:16:43 raspberrypi homebridge[3535]: [11/2/2020, 2:16:43 PM] Loaded plugin: homebridge-knx
Nov  2 14:16:43 raspberrypi homebridge[3535]: [11/2/2020, 2:16:43 PM] Registering platform 'homebridge-knx.KNX'

Any help appreciated?

P.S.
homebridge-knx works fine with old homebridge@0.4.53

**Comment by snowdd1** [comment]
Have a look at the closed issue regarding homebridge 1.x there is a configuration change required.

**Comment by migabc** [comment]
So the solution is just to add a platform section in config.json?
Thanks I try that.
