### ISSUE TITLE
HomeKit Sensor Status

### ISSUE THREAD

**Issue by CyberChris79** [snowdd1/homebridge-knx#193]
Hello,

when i open a window and my HomeKit App is open, the status does not update. Only when i close the HomeKit App and open it again, the new status is shown.

How can i fix that issue?

Thanks a lot

Christian

**Comment by snowdd1** [comment]
Without knowing the configuration of both KNX devices *and* homebridge-knx I can only guess:

The address you put into `listen` is not an active feedback but "query only" and requires a read request on the bus - that is what homebridge-knx does upon starting up, but not frequently. Use ETS to configure the sensor to send active status notifications, and use that address in `listen`.

As I said, my best guess.

**Comment by CyberChris79** [comment]
Hello Raoul,

thank you very much for your fast reply.
My knx_config looks like:

`{
            "DeviceName": "Fenster rechts Gemeinschaftsraum",
            "Services": [
                {
                    "ServiceType": "ContactSensor",
                    "ServiceName": "Fenster rechts Gemeinschaftsraum",
                    "Handler": "ContactSensor",
                    "Characteristics": [
                        {
                            "Type": "ContactSensorState",
                            "Listen": [
                                "1/1/199"
                            ]
                        }
                    ],
                    "LocalConstants": {
                        "Reverse": false
                    },
                    "subtype": "SUB_a8da79d7-5275-4c22-a27e-a9eedd1c3a45"
                }
            ],
            "UUID": "3081ee86-fed6-44ab-a685-1b90f9720193"
        },
`

The status of the window contact is send by a Telenot Security System, which got an KNX Gateway to retrieve the telegrammes.
So, if i look at the security App it refreshes the status everytume i open or close the window, but bot through homebridge-lnx.
There is no option to configure in ETS, cause the Telenot KNX Gatway sends everytime everything to the knx bus, when a change happens.

Greetings
Christian

**Comment by CyberChris79** [comment]
Hello Raoul,

thank you for your fast answer.
I could fix this, so you can close the Issue.

Greetings
Christian
