### ISSUE TITLE
strange issue with Siri voice command.

### ISSUE THREAD

**Issue by marcobastianon** [snowdd1/homebridge-knx#195]
hi all, i'm here with a strange problem.

i create a device with "ServiceType": "Door", named "gate".. the device work correctly if i press the icon.
if i press open i can see on knx the right telegram and same if i press close.

but if i try to activate this device from siri "siri, open gate" she say "device is open", but nothing on knx.

if i remame the device it work.. i'v no other device with the same name .. is it maybe something on caches?

**Comment by snowdd1** [comment]
Sounds strange -maybe "gate" is a reserved word for Siri?
I only use Garage Door devices as physical doors, and those work pretty good in iOS14.4
