### ISSUE TITLE
Dooropener

### ISSUE THREAD

**Issue by petkoe** [snowdd1/homebridge-knx#20]
Hello Raoul,

i have a door with an automatic lock. Currently i have it on a knx which uses a data type 1.017 (Auslöser). It just sends an 1 to the knx address and then opens the door. What would you use to achieve the same on home bridge.

Cheers

Peter

**Comment by snowdd1** [comment]
First of all, are you sure you want to take the risk that Siri opens the door as a result of a misunderstood (or misinterpreted) command?

If you want to go for it:
Currently on the fly mapping is not yet supported in homebridge-knx. For the types  for which HomeKit uses an integer coded value, as for the door lock, see README, you have to use some extra logic module on the bus, such as a Logic module that comes with a device (I learned that some wheather stations have logic modules), a Gira HomeServer, a LinKNX installation (but I am not sure about that one), or other.

As my younger son has been diagnosed leukemia last week I will probably not be able to develop homebridge-knx any further in the next two months at least. I will spend as much time as possible with my sons at home and in the hospital.

**Comment by petkoe** [comment]
Hello Raoul,

re open door: You are right.

I wish you and your family all the best and cross my fingers that your son will get better soon. 

Kind regards 

Peter
