### ISSUE TITLE
GarageDoorOpenerAdvanced Rückmeldung Kontakt funktioniert nicht richtig

### ISSUE THREAD

**Issue by burneemac** [snowdd1/homebridge-knx#207]
Hallo zusammen,

ich habe die KNX-Homebridge schon seit Jahren am Laufen. Seit einem Umzug auf eine neue VM Anfang letzten Jahres, habe ich Homebridge inkl. alle Plugins auf den neusten Stand gebracht. 

Seit dem habe ich das Problem, dass meine beiden Tore die Rückmeldung des Magnetkontaktes der Geschlossenmeldung nicht mehr mitbekommen. Ich habe jeweils nur einen Magnetkontakt, der Andere wird simuliert, was auch funktioniert. Ich habe im Moment parallel eine einfachen Sensorkontakt in die Config eingebaut, welcher die gleiche Gruppenadresse abhört. Hier stimmt alles. 

Ich hänge mal den Auszug meiner Config, vllt. kann mir jemand sagen was ich falsch mache. Danke vorab für die Unterstützung.

Beste Grüße
Burnee

```
{
                    "ServiceType": "GarageDoorOpener",
                    "Handler": "GarageDoorOpenerAdvanced",
                    "ServiceName": "Hoftor",
                    "Characteristics": [
                        {
                            "Type": "CurrentDoorState"
                        },
                        {
                            "Type": "TargetDoorState"
                        }
                    ],
                    "KNXObjects": [
                        {
                            "Type": "KNXPulseUp",
                            "Set": "1/1/192",
                            "Listen": "1/1/192",
                            "DPT": "DPT1"
                        },
                        {
                            "Type": "KNXPulseDown",
                            "Set": "1/1/193",
                            "Listen": "1/1/193",
                            "DPT": "DPT1"
                        },
                        {
                            "Type": "KNXDoorClosed",
                            "Listen": "0/4/190",
                            "DPT": "DPT1"
                        }
                    ],
                    "KNXReadRequests": [
                        "0/4/190"
                    ],
                    "LocalConstants": {
                        "simulateDoorContactMode": "internal",
                        "doorContactPresent": "closed",
                        "staircaseFunc": false,
                        "separatePulseUpDown": true,
                        "sensorOn": 1,
                        "pulseLength": 500,
                        "doorRunTime": 18500
                    }
                }
```

**Comment by giase82** [comment]
Hi, 

Ich habe vor nicht allzu langer Zeit nochmal was geändert. Dazu gibt es einen pull-request: 
https://github.com/snowdd1/homebridge-knx/pull/204

Tritt das Problem immer auf oder nur nach dem init? Hast du ein debug-log-file?

Gruß,
//giase

**Comment by burneemac** [comment]
Moin,

leider immer. Bis dato musste ich noch nie was debuggen. Wo finde ich das log-file?

Gruß
Burnee

**Comment by giase82** [comment]
Servus,

Das kommt auf deine Homebridge-Installation an. Du musst im Debug Mode ( -D) starten und dann vielleicht in `/var/lib/homebridge/homebridge.log` (in meinem Fall).

//giase

**Comment by burneemac** [comment]
N'abend,

das mit dem Debugmodus habe ich noch nicht hinbekommen. Normalerweise läuft Homebridge ja als Service im Hintergrund. Diesen hatte ich mit `systmctl` gestoppt und im Terminal dann mit `homebridge -D` neu gestartet. Im Terminalfenster hat das zunächst gut ausgesehen. Aber scheinbar wurden keinerlei Plugins geladen oder eine anderes Problem liegt vor. 

Auf jeden Fall konnte ich das Webinterface nicht erreichen und in Apple Home waren auch alle Geräte offline. Im Webinterface läuft ja das Protokoll mit, hilf das vllt. weiter?

burnee

**Comment by burneemac** [comment]
Ich nochmal, scheinbar ist das LOG aktiviert. Habe eine Datei von heute gefunden. Anbei ein Auszug:

[homebridge.log](https://github.com/snowdd1/homebridge-knx/files/10796279/homebridge.log)

**Comment by burneemac** [comment]
Salute! 

> Servus,
> 
> Das kommt auf deine Homebridge-Installation an. Du musst im Debug Mode ( -D) starten und dann vielleicht in `/var/lib/homebridge/homebridge.log` (in meinem Fall).
> 
> //giase

Salute! Konntest du dir das Log mal anschauen und evtl. was ausfindig machen?

**Comment by giase82** [comment]
Servus,

Sorry, hat ein bisschen gedauert. Zeigt das log das Fehlverhalten?

Ich frage, weil eigentlich alles zu stimmen scheint. Hier sind zwei Beispiele für den KNX-Sensor.
`INFO undefined: on KNX Value Change(KNXDoorClosed, old=0, new=1)`
`INFO undefined: on KNX Value Change(KNXDoorClosed, old=1, new=0)`

Hast do schonmal eine andere App ausprobiert, um die Anzeige zu überprüfen? Ich habe festgestellt, dass die Home-App da manchmal Probleme hat.

Du könntest auch noch folgende Zeile zu den "LocalConstants" hinzufügen:
`"debugName": "Garagentor"`

Dann steht da "INFO Garagentor" anstatt "INFO undefined".

Hoffe das hilft ein bisschen.

Gruß,
//giase

**Comment by giase82** [comment]
Mir ist beim review des relevanten codes noch was aufgefallen:

Die debugInfo aus dem aktuellen Plugin scheint bei dir nicht da zu sein. z.B. "In if-case -> ... ". Bist du sicher, dass du die neuesten addins hast?

			console.log('INFO ' + this.debugName + ': In if-case -> field===KNXDoorClosed');
			console.log('INFO ' + this.debugName + ': knxValue: ' + knxValue);
			console.log('INFO ' + this.debugName + ': oldValue: ' + oldValue);`

**Comment by burneemac** [comment]
Hi,
das mit dem Debugname werde ich mal noch machen. 

Ja, in anderen Apps sieht es genau so aus.

Großes Problem bei der ganzen Sache ist ja, dass wenn ich das Tor in der Home App oder via Siri öffne, dann aber über die eigene Steuerung des Garagentores schließe, der Status nicht mehr nachgeführt wird und ich das Tor bei dieser Konstellation dann nicht mehr über Apple Home (oder Siri oder sonstige HomeKit App) öffnen kann. Dann muss ich es erst einmal schließen und dann kann ich es auch wieder öffnen. Das ist mega nervig.

Betreffend deines zweiten Posts: wie kann ich kontrollieren welche Version der Addins ich habe, bzw. wo finde ich die Addins?

Danke schonmal für deine Unterstützung.

**Comment by snowdd1** [comment]
`GarageDoorOpenerAdvanced` wurde durch @christof-fersch aktualisiert, Version 0.4.3, aus PR #204

**Comment by burneemac** [comment]
Hi zusammen,

nach der Aktualisierung auf v0.4.3 läuft wieder alles rund. 

Schönen Abend.

**Comment by giase82** [comment]
Super, freut mich!
