### ISSUE TITLE
Open Door works, close not.

### ISSUE THREAD

**Issue by gjniewenhuijse** [snowdd1/homebridge-knx#21]
I added a door opener, with the dutch name Hek (gate).

When i say: Doe het hek open (open the gate), it works
When i say: Doe het hek dicht (close the gate), it doesn't work and siri says: can't find devices

I have the same device for my garage deur (door) and this works great.

Here my device:
`{
					"accessory_type": "knxdevice",
					"description": "sample garage door opener",
					"name": "Hek",
					"services": [
						{
							"type": "GarageDoorOpener",
							"name": "Hek",
							"CurrentDoorState": {
                                "Listen": ["5/0/3"]
                            },
							"TargetDoorState": {
								"Set": "5/0/2"
							}
						}
					]
				}`

**Comment by snowdd1** [comment]
"Can't find devices" sounds like an Siri/Homekit Problem to me. Did you try Setting the Siri language to english and test if it is reliably failing?

**Comment by snowdd1** [comment]
Siri issue, closed.
