### ISSUE TITLE
homebridge-knx 0.2.6 doesn't work with homebridge 0.3.0

### ISSUE THREAD

**Issue by sebbm** [snowdd1/homebridge-knx#24]
homebridge-knx 0.2.6 doesn't work with homebridge 0.3.0.

ERROR LOADING PLUGIN homebridge-knx:
Error: Plugin /usr/local/lib/node_modules/homebridge-knx requires a HomeBridge version of ^0.2.0 which does not satisfy the current HomeBridge version of 0.3.0. You may need to upgrade your installation of HomeBridge.

kind regards,
Marcus

**Comment by snowdd1** [comment]
Hi Marcus,
I have not tested the compatibility yet, if you like you may test it by editing the package.json.
In the "engines" section is an entry "Homebridge":"^0.2.0", if you change that to "^0.3.0" you can try to start it again.
I am currently working on a completely new version, I had no time to check the compatibilty yet.

**Comment by gjniewenhuijse** [comment]
looks like it works

**Comment by snowdd1** [comment]
Ok, I'll change the setting in the repo.
