### ISSUE TITLE
Error connecting knxd

### ISSUE THREAD

**Issue by gjniewenhuijse** [snowdd1/homebridge-knx#3]
I received an error when i start homebridge.

I have a running local knxd connected to a knx gateway at 192.168.2.6 with the following opts: 
KNXD_OPTS="-u -b ipt:192.168.2.6"

My log:

pi@homekit ~ $ homebridge
Homebridge is running on port 51826.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826

**Comment by snowdd1** [comment]
Hi there is some other service already using that port. Probably killed another instance with ctrl-z instead of ctrl-c? That is only pausing the program and not killing it. 
I simply propose to restart your pi to free the port.

If the problem persists, you'll need some Linux guru (or google) to find out what process is occupying the port 51826.

**Comment by gjniewenhuijse** [comment]
HAP-Nodejs was running, now its closed, but now i get the following error. If i read google they say its a knxd connection problem, but how to check this.

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Loaded plugin: homebridge-knx
Registering platform 'homebridge-knx.KNX'
---
Loaded config.json with 0 accessories and 1 platforms.
---
Loading 1 platforms...
[KNX] Initializing KNX platform...
[KNX] Fetching KNX devices.
[KNX] parsing acc 0 of 1
[KNX] push new universal device Tafel lamp
[KNX] Accessory constructor called
[KNX] created Tafel lamp universal accessory
[KNX] returning 1 accessories
[KNX] Initializing platform accessory 'Tafel lamp'...
[KNX] Preparing Services: 1
[KNX] Preparing Service: 0 of type Lightbulb
[KNX] [Tafel lamp]:Lightbulb on/off characteristic enabled
[KNX] knx registering BOOLEAN 2/1/2,2/4/2
[KNX] [Tafel lamp]:[On]: Issuing read requests on the KNX bus...
[KNX] [knxdevice:knxread] preparing knx request for 2/1/2
[KNX] [knxdevice:knxread] preparing knx request for 2/4/2
[KNX] [Tafel lamp]:Lightbulb Brightness characteristic enabled
[KNX] knx registering PERCENT 2/3/2,2/5/2
[KNX] [Tafel lamp]:[Brightness]: Issuing read requests on the KNX bus...
[KNX] [knxdevice:knxread] preparing knx request for 2/3/2
[KNX] [knxdevice:knxread] preparing knx request for 2/5/2
>>> knxd groupsocketlisten starting <<<
Loading 0 accessories...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ââââââââââââââ
    â 031-45-154 â
    ââââââââââââââ

Homebridge is running on port 51826.
(node) warning: possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Socket.addListener (events.js:239:17)
    at Socket.Readable.on (_stream_readable.js:655:33)
    at Connection.openTGroup (/usr/local/lib/node_modules/homebridge-knx/node_modules/eibd/lib/connection.js:142:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-knx/index.js:458:20)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at onwriteError (_stream_writable.js:304:10)
    at onwrite (_stream_writable.js:322:5)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at fireErrorCallbacks (net.js:442:13)
_stream_writable.js:243
function decodeChunk(state, chunk, encoding) {
                    ^

RangeError: Maximum call stack size exceeded
    at decodeChunk (_stream_writable.js:243:21)
    at writeOrBuffer (_stream_writable.js:256:11)
    at Socket.Writable.write (_stream_writable.js:207:11)
    at Socket.write (net.js:618:40)
    at Connection.sendRequest (/usr/local/lib/node_modules/homebridge-knx/node_modules/eibd/lib/connection.js:187:15)
    at Connection.openTGroup (/usr/local/lib/node_modules/homebridge-knx/node_modules/eibd/lib/connection.js:144:8)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-knx/index.js:458:20)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at onwriteError (_stream_writable.js:304:10)
pi@homekit ~ $

**Comment by c-o-m-m-a-n-d-e-r** [comment]
having the same error ...

**Comment by gjniewenhuijse** [comment]
Problem solved: added -i to the knxd opts, to add a listener

**Comment by snowdd1** [comment]
The event emitter problem occurs if node-eibd, which is a module used bro homebridge-knx, is unable to connect to the KNX daemon. 
If your knxd is running properly, it usually is a ip/port/ or firewall topic.

**Comment by c-o-m-m-a-n-d-e-r** [comment]
yeahr i got i run today... was my mistake ... was switching my servers and forgot to change IP in script ... sorry :)

**Comment by snowdd1** [comment]
Glad to hear that.
