### ISSUE TITLE
config-example.json GarageDoorOpener

### ISSUE THREAD

**Issue by giase82** [snowdd1/homebridge-knx#34]
The value for "TargetDoorState" should be "Set" not "Listen" (Correct?)

**Comment by gjniewenhuijse** [comment]
{
					"accessory_type": "knxdevice",
					"description": "sample garage door opener",
					"name": "Garagedoor",
					"services": [
						{
							"type": "GarageDoorOpener",
							"name": "Garagedoor",
							"CurrentDoorState": {
                                "Listen": ["15/1/3"]
                            },
							"TargetDoorState": {
								"Set": "15/1/2"
							}
						}
					]
				}

**Comment by snowdd1** [comment]
stale or solved.
