### ISSUE TITLE
Strange Racecondition

### ISSUE THREAD

**Issue by PP19** [snowdd1/homebridge-knx#35]
Hello,

I get some strange race condition, I have two lightbulbs:

>config
 "services":[

               {
                     "type":"Lightbulb",
                     "name":"Küche",
                     "On":{
                        "Set":"0/0/3",
                        "Listen":[
                           "0/2/3"
                        ]
                     },
                     "Brightness":{
                        "Set":"0/7/1",
                        "Listen":[
                           "0/2/3"
                        ]
                     }
                  },
                  {
                     "type":"Lightbulb",
                     "name":"Wohnzimmer",
                     "On":{
                        "Set":"0/0/2",
                        "Listen":[
                           "0/2/2"
                        ]
                     },
                     "Brightness":{
                        "Set":"0/7/0",
                        "Listen":[
                           "0/2/2"
                        ]
                     }
                  }

Both should behave the same way, but "Küche" doesn't work, if I set "Küche" to 15% for example, it just switches to 100%.

So i debugged the issue and found the error using Busmonitor in ETS:
![bildschirmfoto 2016-08-18 um 9 16 36 pm](https://cloud.githubusercontent.com/assets/2048434/17787463/8789f932-6589-11e6-82c5-636df8df83bd.png)

As you can see, set and on is in the wrong order, but why?

Thx,

Patrick

**Comment by snowdd1** [comment]
Hi Patrick, 
I think HomeKit should not send an ON command at all when controlling brightness. At least it doesn't do in my configuration. 
I noticed you use the same response addresses (Rückmeldeadressen) for both On and Brightness - that is very strange as On is DPT1 (1 bit Boolean) and Brightness is DPT5 (8 bit integer )

I think you should fix these and try again. 

Best regards 
Raoul

**Comment by coliflower** [comment]
Hi Patrick,

as Raoul already wrote, I will need a different GA on different KO of your dimmer for Brightness/Listen.

Have a nice day !
Dariusz

**Comment by PP19** [comment]
Hi, 

Thx for your help, but its the same behavior:

 "type":"Lightbulb",
                     "name":"Kuche",
                     "On":{
                        "Set":"0/0/3",
                        "Listen":[
                           "0/2/14"
                        ]
                     },
                     "Brightness":{
                        "Set":"0/7/1",
                        "Listen":[
                           "0/2/3"
                        ]
                     }
                  },

![bildschirmfoto 2016-08-20 um 5 06 33 pm](https://cloud.githubusercontent.com/assets/2048434/17831982/7f40f8c8-66f8-11e6-9978-137df94694c5.png)

**Comment by snowdd1** [comment]
Hi Patrick,
I just made a group monitor screenshot of the addresses thatare sent when I change the brightness using Homekit.

![image](https://cloud.githubusercontent.com/assets/11786396/17925028/8c4dbd9e-69eb-11e6-8d6c-ac7f2a4cde97.png)

As you can see there is no ON (EIN) command, only a ON response. You might have somehow mixed the response addresses or something. Homekit (and homebridge-knx) does not send the ON if the brightness is changed. I know that this is different with Hue Bulbs that require the ON *before* they accept brightness values.
So I do not know where the ON is coming from in your configuration!

Regards
Raoul

**Comment by snowdd1** [comment]
No traffic on that issue - stale, closing.
