### ISSUE TITLE
Version 0.2.0 does not like home bridge 0.4.1

### ISSUE THREAD

**Issue by petkoe** [snowdd1/homebridge-knx#38]
I just tried the new version of home bridge and hap and home bridge-knx throws an error

>Error: Plugin /usr/local/lib/node_modules/homebridge-knx requires a HomeBridge version of ^0.3.0 >which does not satisfy the current HomeBridge version of 0.4.1. You may need to upgrade your >installation of HomeBridge.

kind regards

Peter

**Comment by neonightmare** [comment]
same behavior on my raspi, just updated homebridge to use ffmpeg plugin, now knx is broken.

thx neo

**Comment by murelli146** [comment]
Selbes Problem mit Homebridge 0.4.5 (Update wegen iOS10)

Gruß Gernot

**Comment by snowdd1** [comment]
0.2.8 is now using homebridge 0.4.x
