### ISSUE TITLE
Knx Listen stops working after some time

### ISSUE THREAD

**Issue by gjniewenhuijse** [snowdd1/homebridge-knx#4]
I have a working Homebridge to KNX connection, set and listen knx commands works. 

But after some time (+- 1 minute) the listen commands stops working and no received commands are handled. 

If i restart homebridge it works again for some time.

```
"platforms": [
        {
            "platform": "KNX",
            "name": "KNX",
            "knxd_ip": "127.0.0.1",
            "knxd_port": 6720,
            "accessories": [
                {
                    "accessory_type": "knxdevice",
                    "description": "Only generic type knxdevice is supported, all previous knx types have been merged into that.",
                    "name": "Tafel lamp",
                    "services": [
                        {
                            "type": "Lightbulb",
                            "description": "iOS8 Lightbulb type, supports On (Switch) and Brightness",
                            "name": "Tafel lamp",
                            "On": {
                                "Set": "2/1/2",
                                "Listen": [
                                    "2/4/2"
                                ]
                            },
                            "Brightness": {
                                "Set": "2/3/2",
                                "Listen": [
                                    "2/5/2"
                                ]
                            }
                        }
                    ],
                    "services-description": "Services is an array, you CAN have multiple service types in one accessory, though it is not fully supported in many iOS HK apps, such as EVE and myTouchHome"
                }
            ]
        }
    ],
```

**Comment by snowdd1** [comment]
Could you please post the log here or as a Gist (better readable) ?

**Comment by snowdd1** [comment]
And, are the lamps in Eve or your HomeKit app inaccessible?
If your start a browser pointing at the pi port 3000, can you see the bus values still changing if you work a wall switch?

**Comment by gjniewenhuijse** [comment]
Nope, the lamps are accessible in my HomeKit app (Insteon+), and i can turn my lamp on/off. 
But when i toggle my wall switch nothing happens in the browser(port3000) and in my homekit app.

Here a short log:
[KNX] [knxdevice:knxread] knx request sent for 2/1/2
[KNX] [knxdevice:knxread] knx request sent for 2/4/2
[KNX] [knxdevice:knxread] knx request sent for 2/3/2
[KNX] [knxdevice:knxread] knx request sent for 2/5/2
[KNX] [Tafel lamp]: Received value from bus:0 for 2/5/2 from 2.2.20 of type DPT5 for Brightness

As you can see there is a received value from the bus, but now it stops receiving telegrams, but sending telegrams is possible. No error in the logging.

**Comment by snowdd1** [comment]
By "sending is possible" you mean you still can switch the lamp using a HomeKit app? 
Only the status doesn't get updated as no telegrams are received by homebridge via knxd?

**Comment by gjniewenhuijse** [comment]
Yes  i can switch the lamp with the homekit app and Siri.

And yes, no status telegrams are received by homebridge via knxd.

**Comment by gjniewenhuijse** [comment]
It looks like a KNXD issue, because when i execute:
sudo systemctl status knxd.service -l

First output:
â knxd.service - KNX Daemon
   Loaded: loaded (/lib/systemd/system/knxd.service; enabled)
   Active: activating (start) since Mon 2015-11-09 10:20:33 UTC; 43s ago
 Main PID: 1413 (knxd)
   CGroup: /system.slice/knxd.service
           ââ1413 /usr/bin/knxd -e 2.1.242 -u -i -b ipt:192.168.2.6

Some minutes later:
â knxd.service - KNX Daemon
   Loaded: loaded (/lib/systemd/system/knxd.service; enabled)
   Active: activating (start) since Mon 2015-11-09 10:22:14 UTC; 56s ago
 Main PID: 1490 (knxd)
   CGroup: /system.slice/knxd.service
           ââ1490 /usr/bin/knxd -e 2.1.242 -u -i -b ipt:192.168.2.6

There is a changed PID, so i think the service is automatically restarted after a crash or something else.

**Comment by snowdd1** [comment]
Makes sense. For sending values **to** the bus we currently open a new connection for each (still considering this only a second best solution, but it still works); For accepting telegrams **from the bus** we open a connection with a bus monitor and keep that open. If knxd crashes in the background and is restarted automatically (I do not have this on my raspi; I started it as a program with *nohup* and have it running since this summer! on a dedicated raspi1b) the bus monitor would not receive any telegrams any more. If have to figure out if it gets informed of the connection loss anywhere to print an error to the log.

You probably should try to get some more information out of the knxd process and its dying. Maybe smurfix (lead developer at knxd) can help you with that, and maybe it's something they need to fix in the knxd.

Looking at the PIDs in your example (1413 and 1490) there seem to be lot of terminated processes in between!

**Comment by gjniewenhuijse** [comment]
Thanks.

I stopped using the systemctl knxd.service and started knxd as program and now it looks like knxd is not crashing every x seconds. But how to start knxd on startup, i'm not a Linux guru :)

I try to inform smurfix about this problem, maybe he has a solution.

**Comment by snowdd1** [comment]
My raspberry is simply running all the time, and is connected to an inexpensive APC UPS for initerrupted 24/7 operations. If I nned to restart the raspberry (for security updates e.g.) I manually restart the knxd as well.
Had no time to invest more work into that yet.

**Comment by snowdd1** [comment]
Hi, was smurfix able to solve your issue? I didn't see any of that floating by for some time.

**Comment by gjniewenhuijse** [comment]
hello, i didn't contact smurfix. I tried your first solution for manual starting knxd and homebridge like this:
cd /home/pi/homekit
nohup /usr/bin/knxd -e x.x.xxx -u -i -b ipt:x.x.x.x &> knxd.out&
nohup homebridge &> homebridge.out&

and it works now, next is finding a way to start this commands with init.d

many thanks for all the hard work, its a very nice knx solution with homebridge.

**Comment by snowdd1** [comment]
You're welcome.
