### ISSUE TITLE
GIRA WIndowCovering

### ISSUE THREAD

**Issue by petkoe** [snowdd1/homebridge-knx#41]
Hallo,

is anybody using the window covering with the gira actor

{
"name": "rolladen arbeitszimmer",
"services": [
{
"CurrentPosition": {
"Listen": "4/2/8R"
},
"Targetposition": {
"Set": "4/2/9R"
},
"name": "rolladen arbeitszimmer",
"type": "WindowCovering"
}
]
},

I get back the position but cannot move them up or down

with the gira app it works.

Short (Kurzzeitbetrieb) 4/2/7
Long (Langzeitbetrieb) 4/2/6
Pos 4/2/9
Feedback (Rückmeldung) 4/2/8 

Thanks 

Peter

**Comment by snowdd1** [comment]
Hi Peter, I have the same set up (also Gira Jalousie-Actor) and it works. What is the reaction if you change the target position using HomeKit?

**Comment by petkoe** [comment]
Hallo Raoul,

there is no reaction. I have now just two accessories for a test environment. A lamp and the windows cover. I can switch the lamp on/off or set the brightness. I receive the pos of the shutter but cannot set it. There is no reaction. Setting the position from the gira app I received the new position from the bus. Can you verify that I have set the correct addresses.

Thanks 

Peter

**Comment by snowdd1** [comment]
Hello Peter!
I used 
```
{
	"name": "Bürorollo Links",
	"services": [
		{
			"type": "WindowCovering",
			"name": "Bürorollo links",
			"TargetPosition": {
				"Set": "2/3/46"
			},
			"CurrentPosition": {
				"Listen": "2/3/26"
			}
		}
	]
},
```
In ETS it looks like: 
![image](https://cloud.githubusercontent.com/assets/11786396/19213445/28c2a064-8d6d-11e6-87d7-c07b1aaf4762.png)
It's a "Jalousieaktor 8fach" Gira 2161 00
Hope that helps.
Raoul

**Comment by petkoe** [comment]
Hello Raoul,

nope. It looks identical to mine. I have the same setup. I just removed the "R" from the addresses. I have now a second one added to my test in case somethings wrong but i am not able to move the cover down. 
I get the correct position but cannot move. In the terminal I see nothing when using the home app. I deleted everything in .homebridge, removed the home from my phone ...

Do you have a way to debug? 

Peter

**Comment by snowdd1** [comment]
Hi Peter, 
I just saw you wrote "Targetposition" instead of "Target**P**osition" (upper case "P" as in "Peter" - sorry couldn't resist 😄 )
Please try with capitalized P!
Regards
Raoul

Sorry for the program being so stupid, but it simply compares the strings to Homekit definitions, and that binary.

**Comment by petkoe** [comment]
Hallo Raoul,

thanks with a big T 👍 

It is working now. 

Peter

**Comment by snowdd1** [comment]
BTW there should have been some kind of warning at start-up. But there aren't, as the current 0.2.x version actively looks for the right properties, and thus neglects everything else that could be in there.  
Next version 0.3 will be different.  
However, that means a lot of work for me - and for you, because the config format is different...

**Comment by petkoe** [comment]
If I can help you with testing. I have a second installation on my Mac and some basic excel file for "calculating" the config.json. I can also setup a virtual machine for testing.
