### ISSUE TITLE
Add DPT for current and energy (strommessung und verbrauch)

### ISSUE THREAD

**Issue by hyperbart** [snowdd1/homebridge-knx#42]
Would be nice to have the mA and kWh measurement added to outlets in Homekit.

**Comment by snowdd1** [comment]
Hi @hyperbart 
I just looked up the outlet service in Homekit, and it supports "On" and "OutletInUse" characteristics.
I didn't see any "current" or "energy" characteristics in the list either: 
https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js

```javascript
/**
 * Service "Outlet"
 */

Service.Outlet = function(displayName, subtype) {
  Service.call(this, displayName, '00000047-0000-1000-8000-0026BB765291', subtype);

  // Required Characteristics
  this.addCharacteristic(Characteristic.On);
  this.addCharacteristic(Characteristic.OutletInUse);

  // Optional Characteristics
  this.addOptionalCharacteristic(Characteristic.Name);
};
```
Before I add custom characteristics I have to get the rest working.
