### ISSUE TITLE
Version 0.3.0 is in alpha testing state

### ISSUE THREAD

**Issue by snowdd1** [snowdd1/homebridge-knx#43]
Dear intrepid hackers,

those of you who are without fear might now check out the `plugin-2.0` branch at https://github.com/snowdd1/homebridge-knx/tree/plugin-2.0  

It's guaranteed to be full of stupid error, coding mistakes, and anti patterns.

And of course, undocumented to the possible extend, too.

Feedback is welcome!

**Comment by snowdd1** [comment]
## Some changes:

- config file is now separated from `config.json`: it's surprisingly called `knx_config.json` and belongs in the same directory. 
- the config file is written to: homebridge-knx writes `UUID` and `subclass` fields that **must not be changed**
- the syntax has changed: see https://github.com/snowdd1/homebridge-knx/tree/plugin-2.0#knx_configjson

And the best: it is now possible to write small simple add-ins to change service behaviour. More to come!

**Comment by snowdd1** [comment]
### More flexibility: 
You can now add **any** characteristic to **any** service. As long as it doesn't break Homekit, it is possible. There is no fixed characteristics list any more.

That comes at a price of course: Some of the prepared services of version 0.2 had implicit logical mappings. They're gone of course.

So we need little **add-ins** for special mappings (see the [example](https://github.com/snowdd1/homebridge-knx/blob/plugin-2.0/lib/addins/GiraJalousieActuator.js)!)

**Comment by petkoe** [comment]
Hi Raoul,

it looks very interesting. I should have time tomorrow to try a first install and give feedback. 

Thanks for your work.

Peter

**Comment by petkoe** [comment]
Hi Raoul,

I have the new version installed and created a knx_config.json with a window cover (Rolladen) and a light. Homebridge starts and seems to work. When I get home I will try it out

I have a excel file where I build the json and can refine the formulas for the json. I will updating the formulas following any changes from you and can upload it here ? 

Peter
[homebridge_fritzbox_cmd.xlsx](https://github.com/snowdd1/homebridge-knx/files/524113/homebridge_fritzbox_cmd.xlsx)

**Comment by snowdd1** [comment]
Hi Peter 
ich habe den letzten Satz nicht verstanden.

**Comment by petkoe** [comment]
Hi Raoul,

sorry 
Mal auf Deutsch :-). Ich hatte eine Exceldatei angehängt mit Blättern für das Erstellen der JSON aus den verschiedenen KNX Objekten. Das ist nur ein erster Entwurf und kann auch für alle anderen die Testen eine Basis sein. Eigentlich kann man die Adressen in den verschiedenen Blättern ändern, die Formeln nach unten ziehen etc. Dann kommt auf dem ersten Blatt in A1 das komplette JSON für die Config raus. Das ganze ist halt auch erst Alpha und ich passe die Formeln dann an. 

Viele Grüße,

Peter

And now to the first test: Homebridge starts on my Mac but I get a timeout with the new plugin while pairing my iPhone with it. Before I installed the alpha I was able to pair. I had no more time but will try further the next days.

**Comment by petkoe** [comment]
Hi Raoul,

I have it working with 3 GAs  ok. Will do more later.

Peter

**Comment by snowdd1** [comment]
Great! Any idea what the pairing issue was?

**Comment by petkoe** [comment]
I think one of the other plugins I was testing. I removed all other plugins.

**Comment by snowdd1** [comment]
Alpha and Beta testing ended.
