### ISSUE TITLE
Version 0.3.0 Problem with cached accessories

### ISSUE THREAD

**Issue by misc2000** [snowdd1/homebridge-knx#45]
hi,
when I modify the services of a device in the knx_config.json and for example remove a services this service will still show up even when you restart homebridge for ever. Also after x modifications.

As work around you need to delete this file  
accessories/cachedAccessories 
or / or files in persist folder
by hand during homebridge is stoped.

I think this should not be the case...

**Comment by snowdd1** [comment]
It's a topic of the new homebridge plugin structure. I need to implement an accessory remover that can erase single accessories without deleting all of the data.

**Comment by snowdd1** [comment]
Now there is a tiny webserver at `{yourIp}:18081/list` that shows which devices (accessories) are in the homebridge cache:
```
Restored devices from homebridge cache:

Device Arbeitszimmerlampe
Device Arbeitszimmerrollo
Device TestDevice
```
Next step is to make them deletable.

**Comment by misc2000** [comment]
OK I will take a look tomorrow.
But whats about making a hash over the device configuration and store it together also.
And compare this hash every time homebridge is starting up and if the hash is changed during the startup the cache to the device with the changed hash need to be also deleted...

**Comment by snowdd1** [comment]
The hash is already there. I could include a setting to tell homebridge-KNX to remove all accessories that were loaded from cache but are not found in the configuration.   
The UUID fields that homebridge-knx writes to the config are the keys that can be used to identify accessories. That's why users must not change them after first startup.

**Comment by snowdd1** [comment]
Sorry misunderstood your post. You want to re-create the whole device if it was changed. That would mean removing it from any scene, room etc if you change a group address- I don't think that's a good idea.

**Comment by misc2000** [comment]
my idea was to remove devices that are no longer in the config file and more important to remove the cache of changed devices. most time when you try out new things you do step by step modifications on the same device and homebridge do net care this changes inside the device or show the device twice (old and new version) :-(

**Comment by snowdd1** [comment]
Homebridge caches the accessories, and they are identified on startup by their UUID strings (services with their subtype strings). Those strings are written to the knx_config.json.  

So when you change the knx_config you should always start with the version from the homebridge server, and not with a fresh one, because with a fresh knx_config will not match any of the cached devices, and you have all devices twice.  

I will implement the accessory remover that will do both - be able to delete orphaned devices (no config entry) and delete the cache of existing devices in order to reload the device on next startup.

How ever, I will not be able to work on that probably for the next days, until then you will need to delete the accessories folder in the homebridge folder to reload the accessories from the config.

**Comment by misc2000** [comment]
OK Thanks. 
In the past I never copied by the knx_config.json from the RasPI to modify it. I think I need to do it from now.

**Comment by snowdd1** [comment]
I just committed some changes for the cached accessories.
You can now open a browser at **`http://yourServerNameOrIP:18081/list`** and delete accessories from the cache. right now, only accessories that were already in the cache when homebridge started are shown. So you probably need to restart homebridge twice if you want to make changes to a new device.

**Comment by snowdd1** [comment]
Fun thing is: they immediately vanish in Home 😄

**Comment by snowdd1** [comment]
Next push: shows also devices from knx_config.json that were not loaded from cache at startup.

**Comment by misc2000** [comment]
sounds good. I will give it a try right now...

**Comment by misc2000** [comment]
I did try to delete a device from the cache with the web gui and get this error:

/usr/local/lib/node_modules/homebridge/lib/api.js:166
      throw new Error(pluginName + " - " + platformName + " attempt to unregister an accessory that isn\'t PlatformAccessory!");
      ^

Error: undefined - undefined attempt to unregister an accessory that isn't PlatformAccessory!
    at API.unregisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/api.js:166:13)
    at KNXPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-knx/index.js:263:20)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:172:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:527:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)

**Comment by snowdd1** [comment]
Strange. Have to investigate this evening.

**Comment by snowdd1** [comment]
Did you manage to click twice on the `delete` link? Because it got deleted - a second attempt to delete the same accessory will exactly look like your error.

**Comment by misc2000** [comment]
I don't think I clicked twice, but how know. Later on during a second try it worked without a crash.

**Comment by snowdd1** [comment]
Maybe I can see to catch that possibility in the code, later this weekend maybe.

**Comment by snowdd1** [comment]
Caught in latest commit - a little nasty with a try-catch block but should suffice for that.

**Comment by snowdd1** [comment]
All devices that were present at startup occur twice in the list - once as read from cache, and once as read from knx_config.json:  
![image](https://cloud.githubusercontent.com/assets/11786396/19836160/5d1ddcde-9e98-11e6-8dc2-e621aceb1055.png)

**Comment by snowdd1** [comment]
Now you can even restart homebridge - given that you have it running as a systemd service with restart option, or are using forever to restart it if it fails:

![image](https://cloud.githubusercontent.com/assets/11786396/19948197/a4ccfd98-a14b-11e6-9bc8-473a835a52b5.png)

It simply throws an exception ("Committed_Suicide") and that kills the node process as all unhandled exceptions kill it.
