### ISSUE TITLE
Version 0.3.0 Handler onHKValueChange not executed

### ISSUE THREAD

**Issue by misc2000** [snowdd1/homebridge-knx#46]
hi,
I have a problem with my implementation of the my Handler for HK SecuritySystem

I can see and trace the status in the HOME app of my iPhone if a change the state of the Device from the KNX side.
But if I change the State of the SecuritySystem from the HOME App this should result in a changed "SecuritySystemTargetState" {1...4} but the onHKValueChange Section of my Handler is never executed. Even not when I reduce it to a log line only :-(

ABBSecuritySystem.js:
...
	onHKValueChange(field, oldValue, newValue) {
		console.log('INFO: on HK Value Change (' + field + ", "+ oldValue + ", "+ newValue + ")");
		if (field==="SecuritySystemTargetState") {
			console.log('SecuritySystemTargetState (' + oldValue + ", "+ newValue + ")");
			// The value property of SecuritySystemTargetState must be one of the following:
			// Characteristic.SecuritySystemTargetState.STAY_ARM = 0;
			// Characteristic.SecuritySystemTargetState.AWAY_ARM = 1;
			// Characteristic.SecuritySystemTargetState.NIGHT_ARM = 2;
			// Characteristic.SecuritySystemTargetState.DISARM = 3;
		}
	} // onHKValueChange
...

knx_config.json:
....
"Devices": [
        {
            "DeviceName": "Einbruchmeldezentrale alpha",
            "Services": [
                {
                    "ServiceType": "SecuritySystem",
                    "Handler": "ABBSecuritySystem",
                    "ServiceName": "Alarmanlage Alpha",
                    "Characteristics": [
                        {
                            "Type": "SecuritySystemCurrentState"
                        },
                        {
                            "Type": "SecuritySystemTargetState"
                        }
                    ]
...

**Comment by misc2000** [comment]
After some more test with a other Device (also with a own Handler) I have the same problem.
This time I did implement a Door Lock 
...
"ServiceType": "LockMechanism",
                    "Handler": "AbusDoorLockSystem",
                    "ServiceName": "Türschloss",
                    "Characteristics": [
                        {
                            "Type": "LockCurrentState"
                        },
                        {
                            "Type": "LockTargetState"
                        }
                    ],
...
Status of the Lock is shown right in the HOME App when I change the status from the KNX side.
But all the time when I execute a status change command with the HOME App on the iPhone I don't get any events inside the Homebridge. :-(

**Comment by misc2000** [comment]
I found a Workaround:

you need to assign to all Characteristics that you need to evaluate in the handler a even dummy KNX GA. 

                {
                    "ServiceType": "LockMechanism",
                    "Handler": "AbusDoorLockSystem",
                    "ServiceName": "Türschloss",
                    "Characteristics": [
                        {
                            "Type": "LockCurrentState"
                        },
                        {
                            "Type": "LockTargetState",
                            "Set": "4/4/100",
                            "Listen": "4/4/100",
                            "DPT": "DPT1"
                        }

The KNX GA 4/4/100 do not exit in my installation but will fix the missing events issue for now!

Michael

**Comment by snowdd1** [comment]
Hi Michael,
I found it. Currently a characteristic is only bound to the change event [if it has a "Set"](https://github.com/snowdd1/homebridge-knx/blob/plugin-2.0/lib/characteristic-knx.js#L63) section in the knx_config.json - which is good with the default handler. If you want to do something completely different and you never want to do a  `knxWrite(field, value, dptype)` for that field you probably do not have a `Set` - as in your stubs above.
I need to fix that.
Raoul

**Comment by snowdd1** [comment]
You were faster!

**Comment by snowdd1** [comment]
Hi Michael,
you can download an updated plugin-2.0 branch to test. Should now call `onHKValueChange()`  on changes.
Raoul

**Comment by misc2000** [comment]
It don't look like it fix my issue so far.
I did remove my workaround and still no events.
Michael

**Comment by misc2000** [comment]
did work now. 
I did forget to delete the cachedAccessories file on my first try...
Michael

**Comment by snowdd1** [comment]
Did you clone the latest version? 
I just rebuilt your test and it shows
```bash
  Accessory [DEVHomebridge] Setting Characteristic "Lock Target State" to value 1 +2ms
  EventedHTTPServer [::ffff:192.168.178.85] Muting event '4.10' notification for this connection since it originated here. +11ms
  DummyHandler INFO: onHKValueChange(LockTargetState, null, 1) +5s
  EventedHTTPServer [::ffff:192.168.178.85] HTTP Response is finished +6ms
  EventedHTTPServer [::ffff:192.168.178.85] HTTP request: /characteristics +2s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +1ms
  Accessory [DEVHomebridge] Processing characteristic set: [{"aid":4,"iid":10,"value":0}] +4ms
  Accessory [DEVHomebridge] Setting Characteristic "Lock Target State" to value 0 +1ms
  EventedHTTPServer [::ffff:192.168.178.85] Muting event '4.10' notification for this connection since it originated here. +5ms
  DummyHandler INFO: onHKValueChange(LockTargetState, 1, 0) +2s
  EventedHTTPServer [::ffff:192.168.178.85] HTTP Response is finished +3ms
```
I'll put the sample files into plugin-2.0 branch.

**Comment by misc2000** [comment]
see my last note...

**Comment by snowdd1** [comment]
sorry, the web page does not update while typing 😒

**Comment by snowdd1** [comment]
Ok, so that's done!
