### ISSUE TITLE
Scenes with dimmer giving issues

### ISSUE THREAD

**Issue by hyperbart** [snowdd1/homebridge-knx#48]
When I activate a scene when all lights are out homebridge-knx sends out the dimming value first and then the ON command.

The result is that the scene gets "greyed out" almost immediately after starting because the dimming value is not according to the scene since it loads the previous dimming value from when the lamp was turned off.

**Comment by hyperbart** [comment]
Bizarre because this used to work before, has something changed on homekit/Home app?

**Comment by hyperbart** [comment]
Hmmm, the lights seem to go to 100%, might have something to do or related to:

https://github.com/snowdd1/homebridge-knx/issues/47

**Comment by snowdd1** [comment]
Have you tried activating the scene with Siri or Eve app?

**Comment by snowdd1** [comment]
We are not alone:  
https://github.com/nfarina/homebridge/issues/807  
https://github.com/nfarina/homebridge/issues/240

**Comment by hyperbart** [comment]
Ah, makes me wonder if native Philips Hue suffers the same problem. The latest gen of bridges shipped with Hue bulbs are natively HomeKit compatible. But since I am moving to my new home this month I already deleted my old Hue based home from homekit. Some things to test though...

**Comment by snowdd1** [comment]
Let's bundle the discussion in https://github.com/snowdd1/homebridge-knx/issues/47
