### ISSUE TITLE
No accessories responding - Restart service solves issue

### ISSUE THREAD

**Issue by hyperbart** [snowdd1/homebridge-knx#55]
Recently moved to my new home with a full KNX setup being 50 accessories in HomeKit.

All my switching or dimming components are MDT units. I have VMware workstation with Ubuntu and Homebridge installed on a laptop (home-server will be installed within a couple of weeks). Wireless network is based on 2 Meraki MR18's.

Recently I have noticed some problems with HomeKit:

"No accessories responding" and the Homebridge states "the accessory is not responding".

Homebridge service is running and no errors:

![image](https://cloud.githubusercontent.com/assets/2131310/19875331/2e368e86-9fcc-11e6-8527-7ac7aa579c53.png)

When I restart Homebridge everythings works fine (for a while). Haven't restarted my service yet, I want to leave it like this to enable troubleshooting.

**Comment by snowdd1** [comment]
For some reason Homebridge was killed. It says `active, ...., exited` in your screenshot. It seams that your session of user KNX is dying in the background. And then, of course, no accessory is responding any more.

**Comment by snowdd1** [comment]
Would be good to see the log of the crash. Can you please search the journal for the date and time it gives in the screenshot and paste the log here ?

**Comment by snowdd1** [comment]
Sorry, I might be wrong - you're obviously using a **sysvinit** with init.d system, not a **systemd** system.
At my raspberry with systemd the same looks like:
```
pi@knxd2-raspberry:~ $ sudo systemctl status homebridge
● homebridge.service - Homebridge Automation Service
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: active (running) since Mo 2016-03-21 12:11:15 CET; 7 months 12 days ago
     Docs: https://github.com/nfarina/homebridge
 Main PID: 3901 (homebridge)
   CGroup: /system.slice/homebridge.service
           └─3901 homebridge

Nov 01 14:41:39 knxd2-raspberry homebridge.service[3901]: [2016-11-01 14:41:39] [KNX] [Bewegung 
```

It says *active (running)* there, not *active (exited)*  

This is my production homebridge, hadn't had (or required) a restart in 7 months!  
Just about to kill the uptime report with the new beta though ...

**Comment by snowdd1** [comment]
stale - closing
