### ISSUE TITLE
RGB Device

### ISSUE THREAD

**Issue by Mit9l** [snowdd1/homebridge-knx#60]
Hi, i have one question about rgb light device
Please, tell me, how i can control rgb device? is it possible?
Thank you

**Comment by snowdd1** [comment]
What GAs does such a lamp need? I don't have one, so I cannot say if it works without additional work, but I heard of people having it done.

**Comment by dosordie** [comment]
The following config works fine with my RGB Stripes (Gira HS Logic converts the values Brightness, Hue and Saturation from HB in 3x 0-100% Red Green Blue KNX/Dali) 

`{
            "DeviceName": "LED Wohnzimmer",
            "Services": [
                {
                    "ServiceType": "Lightbulb",
                    "ServiceName": "LED Wohnzimmer",
                    "Characteristics": [
                        {
                            "Type": "On",
                            "Set": [
                                "1/4/11"
                            ],
                            "Listen": [
                                "1/4/37"
                            ]
                        },
                        {
                            "Type": "Brightness",
                            "Set": [
                                "1/4/40"
                            ],
                            "Listen": [
                                "1/4/40"
                            ],
                            "DPT": "DPT5"
                        },
                        {
                            "Type": "Hue",
                            "Set": [
                                "1/4/41"
                            ],
                            "Listen": [
                                "1/4/41"
                            ],
                            "DPT": "DPT9"
                        },
                        {
                            "Type": "Saturation",
                            "Set": [
                                "1/4/42"
                            ],
                            "Listen": [
                                "1/4/42"
                            ],
                            "DPT": "DPT5"
                        }
                    ],
                    "KNXReadRequests": [
                        "1/4/37",
                        "1/4/40",
                        "1/4/41"
                    ],
                    "subtype": ""
                }
            ],
            "UUID": ""
        },`

**Comment by snowdd1** [comment]
@dosordie : So you're getting a `hue` value and convert it to RGB values?

**Comment by dosordie** [comment]
@snowdd1 
The Values `hue`, `saturation` and `brightness` are needed that Homebridge knows this is an RGB Device. Only "hue" won´t work.

With this values you can calculate the RGB values.

**Comment by snowdd1** [comment]
Do you have a formula for that?

**Comment by dosordie** [comment]
Take a look at this [http://www.rapidtables.com/convert/color/rgb-to-hsv.htm](url)

For me, my Homeserver does that. [https://service.knx-user-forum.de/?comm=download&id=12234](url)

**Comment by snowdd1** [comment]
http://www.rapidtables.com/convert/color/hsv-to-rgb.htm

cool, that's what we can put into an add-in.

**Comment by Mit9l** [comment]
@dosordie @snowdd1 
Thank you for this information.

**Comment by snowdd1** [comment]
@Mit9l Dima, 
can you give me the DPTs for the R,G,B channels?

**Comment by snowdd1** [comment]
I assumed DPT5 (0..255), you might test this draft: 

https://github.com/snowdd1/homebridge-knx/blob/master/lib/addins/RGBLight.js

**Comment by Mit9l** [comment]
at this moment i don't know how i can do this (configure rgb) and i don't know which DPT use. 
oh....i'm crying) my home system based on homebridge-knx 0.2.0. To do this i must update and this is sadness ))))

**Comment by Mit9l** [comment]
at this week i buy sd card, install new plugin and test your draft
thank you for this solution

**Comment by Mit9l** [comment]
Hello, sorry for the long silence, i didn't have a chance....
Today i'm testing the plugin and at the moment the situation next:
this my code:
`{
            "DeviceName": "Room",
            "Services": [
                {
                    "ServiceType": "Lightbulb",
                    "ServiceName": "Room Main Light",
                    "Characteristics": [
                        {
                            "Type": "On",
                            "Set": [
                                "0/0/3"
                            ],
                            "Listen": [
                                "0/6/68"
                            ]
                        },
                        {
                            "Type": "Brightness",
                            "Set": [
                                "0/0/18"
                            ],
                            "Listen": [
                                "0/6/69"
                            ]
                        }
                    ]
                },
                {
                    "ServiceType": "Lightbulb",
                    "Handler": "RGBLight",
                    "ServiceName": "Room rgb",
                    "Characteristics": [
                        {
                            "Type": "On",
                            "Set": [
                            	"1/15/0"
                            ],
                            "Listen": [
                            	"1/15/0"
                            ]
                        },
                        {
                            "Type": "Hue"
                        },
                        {
                            "Type": "Brightness"
                        }
                    ],
                    "KNXObjects": [
                        {
                            "Type": "Red",
                            "Set": "1/15/1",
                            "DPT": "DPT5"
                        },
                        {
                            "Type": "Green",
                            "Set": "1/15/2",
                            "DPT": "DPT5"
                        },
                        {
                            "Type": "Blue",
                            "Set": "1/15/3",
                            "DPT": "DPT5"
                        }
                    ],
                    "KNX-ReadRequests": [
                      "1/15/0"
                    ]
                }
            ]
        }`

RGB doesn't work((( maybe i'm doing something wrong?
I'm write in terminal next command:
knxtool groupswrite local: 1/15/2 255
or
knxtool groupswrite local: 1/15/0 1
and nothing happens.....except for one moment: all devices are not available in iPhone (as if the HomeBrdige is shut down). but after 10-20 seconds all restored.

**Comment by Mit9l** [comment]
There is another point that I believe is important. RGB device (room rgb) added to HomeKit on iPhone, but when i push on him - the same thing happens, all devices are not available...

P.S. Sorry for my english

**Comment by snowdd1** [comment]
Looks as if the response to HomeKit is considered non-compliant. If I find time this evening I will have a look into that.
And for *knxtool group**s**write* - I think for DPT5 you need `knxtool groupwrite` without the `s`, because `s` means short, I think up to 3 bits, and DPT5 is 8 bits long.

**Comment by snowdd1** [comment]
>knxtool groupswrite local: 1/15/2 255  

KNX group addresses **cannot** have values that exceed 31/7/255, so 1/15/2 is illegal! So your code make break there. I am wondering why the group address check did not throw an exception there. How did you get these addresses into your device?

**Comment by snowdd1** [comment]
Ok, found one: The characteristic "Saturation" is required for the service; that was missing in the Documentation - however, that should have led to wrong colors only.

**Comment by Mit9l** [comment]
I'm sorry, not correctly written group addresses here (changed).
1/15/2 -I created this group in ETS
Maybe I do not refer to him properly? 
Maybe something should be written in Suturation?! But i don't now what i can write here....
Tell me please, can i wacth the documentation? can you give me a link?

**Comment by snowdd1** [comment]
Sure, it was in the source file: https://github.com/snowdd1/homebridge-knx/blob/master/lib/addins/RGBLight.js#L92

But as I said, the `{"Type":"Saturation"},` entry is missing next to hue.

**Comment by snowdd1** [comment]
Your room.txt Attachement is also wrong, it contains 1/15/x addresses as well, if that's from your knx_config.json it will break.

I updated the sample config to contain *Saturation* characteristic and added some logging that is written out when you change color in iOS.  
https://github.com/snowdd1/homebridge-knx/blob/master/lib/addins/RGBLight.js#L100  

you can install that patch with `npm install snowdd1/homebridge-knx` or if you have a global installation, with `sudo npm install -g snowdd1/homebridge-knx` 

please report back.

**Comment by Mit9l** [comment]
ok, thanks. I'm testing on the next week and report to you

**Comment by Mit9l** [comment]
Hello, i tested rgb and i want to say - we have some changes. When i push the button (color light) on the iphone - shows color palette. When i select the color he wrote me - device doesn't respond and homebridge is shutdown (

**Comment by snowdd1** [comment]
Can you get some debug output and paste it here?

**Comment by Mit9l** [comment]
Ofcourse, but if you tell me how i can take log file... Or what should I do?
p.s. When i push the button in ETS -> Group Monitoring - nothing shows...

**Comment by snowdd1** [comment]
How do you start homebridge?

**Comment by Mit9l** [comment]
on boot with systemd

**Comment by snowdd1** [comment]
To re-enable your homebridge afterwards you may remove the DEBUG line, and set the `restart` again to `always`. Then 
```
sudo systemctl stop homebridge
sudo systemctl daemon-reload
sudo systemctl enable homebridge
sudo systemctl start homebridge
```

**Comment by Mit9l** [comment]
ExecStart=/usr/bin/node /home/pi/node_modules/homebridge/bin/homebridge -D

Homebridge swear on this line.
HomeBridge I installed globally
knx_config.json and config.json --------  I have is in the     /var/homebridge    folder

**Comment by snowdd1** [comment]
Sorry I meant just add the environment line and edit the restart line. Do not change the other lines of your service file!

**Comment by Mit9l** [comment]
this my debug file.

[rgb-debug.txt](https://github.com/snowdd1/homebridge-knx/files/760162/rgb-debug.txt)

sorry for the not good quality, but the errors you can identify

**Comment by snowdd1** [comment]
Please add a characteristic `Saturation`

**Comment by snowdd1** [comment]
See https://github.com/snowdd1/homebridge-knx/issues/60#issuecomment-275609663

**Comment by Mit9l** [comment]
hello
this is new bug report
[debug.txt](https://github.com/snowdd1/homebridge-knx/files/768123/debug.txt)

**Comment by snowdd1** [comment]
Try `DPT5` instead of `DTP5`

**Comment by Mit9l** [comment]
sorry, but i don't understand...in my file (knx_config.json) only DPT5, i don't have DTP5.

[knx_config.txt](https://github.com/snowdd1/homebridge-knx/files/768376/knx_config.txt)

**Comment by Mit9l** [comment]
oh, i think i understand...DPT5 instead of DTP5 in addins (line 90-91)? 

or adapt to these values in my knx_config.json file ?

**Comment by snowdd1** [comment]
Sorry, didn't see it came from line 90+ from the add in. Thought it was from config. Maybe I can fix it tomorrow, you might change it yourself in your copy to test upfront.

**Comment by snowdd1** [comment]
Just found out I can change that in Github using a web browser, and did that. You might test again.

**Comment by Mit9l** [comment]
i change in my copy and i will try to test today

**Comment by Mit9l** [comment]
Hello. I tested the new version and almost all good, color pallete, brihtness - it works.
Does not work ON/OFF... nothing happens when i click the icon. 
I upload 2 debug file
First not full
[debug_1.txt](https://github.com/snowdd1/homebridge-knx/files/772300/debug_1.txt)

Second  - full
[debug_2.txt](https://github.com/snowdd1/homebridge-knx/files/772304/debug_2.txt)

**Comment by Mit9l** [comment]
Looking at the log file, when you click on the action ON/OFF he sent the wrong data, but how to fix it, I do not know (

**Comment by Mit9l** [comment]
as I understand it, when you turn on it should send 255,255,255 1
when you turn off - 0,0,0,0
but he sends a very different data ...

**Comment by snowdd1** [comment]
Right, it's not yet implemented. 
Does it need to send 0s on all four characteristics, or just for the `On` characteristic? And vice-versa, 255 for all colors and a 1 to the `On` address?

**Comment by Mit9l** [comment]
Look, when i write in terminal **knxtool groupwrite local: 15/1/4 1** all RGB tape ON
          when i write in terminal  **knxtool groupwrite local: 15/1/4 0** all RGB tape OFF
15/1/4 - this is group address, with it i completely turn on or turn off the rgb tape

So i think - "or just for the On characteristic" and "a 1 to the On address"

**Comment by Mit9l** [comment]
Actually i'm not too sure, please give me a time to think

**Comment by snowdd1** [comment]
But it sounds consistent. You just need the `On` characteristic to turn it on or off, and the color triple (Brightness, Saturation, Hue) for color and brightness.  
I'll give it a test shot.

**Comment by Mit9l** [comment]
All the same, i think that should bo controled at 1 address

**Comment by Mit9l** [comment]
Hello
ON - works
OFF - doesn't works

**Comment by snowdd1** [comment]
Though I found there is still an error in logging, would you mind pasting a log of switching on and switching off ?

**Comment by Mit9l** [comment]
of course

[debug_3.txt](https://github.com/snowdd1/homebridge-knx/files/783174/debug_3.txt)

**Comment by snowdd1** [comment]
Sorry didn't find it. Could you make logs off "on" and "off" separately so I can better see what's going on?

**Comment by Mit9l** [comment]
ok, this is updated file

[debug_3.txt](https://github.com/snowdd1/homebridge-knx/files/785879/debug_3.txt)

**Comment by Mit9l** [comment]
Hello 
Raoul,  did you have any ideas?

**Comment by snowdd1** [comment]
Not really. In the German discussions somebody got it to work with his color led stripes (see link to issue 38 above). His problem was at first to have the knxd configured to send the telegrams to fast for his gateway. Might that be an issue for your gateway too?

**Comment by Mit9l** [comment]
In my situation all fine works, nearly....). color pallete - works, situration - works, ON - works, but OFF - doesn't works (when i click on iPhone...)   if i write (in terminal on raspberry pi) **knxtool groupsmonitor local: 15/1/4 0** my rgb device is shuting down

**Comment by Mit9l** [comment]
I connect to bus with TPUART USB interface

**Comment by snowdd1** [comment]
Really strange. Switching OFF with Home app should start with a an entry like 
```
INFO: onHKValueChange(On, 1, 0)
```
But that doesn't appear to be in your log. I can see entries (On, 0, 1) which means switching from 0 off to 1 on, but no off-to-on entries.

**Comment by Mit9l** [comment]
Hello, Raoul!
Everything is working!)
The server was not configured correctly....
I think this issue can be closed
Thank you vary mach for your help

**Comment by snowdd1** [comment]
Thank you for the feedback!
