### ISSUE TITLE
Reverse seems not working

### ISSUE THREAD

**Issue by giase82** [snowdd1/homebridge-knx#62]
Hi,

I recognised that the "reverse" keyword does not change the behaviour of my LockMechanism. The door shows open when closed and the other way around. I tried both of the following configurations. What am I doing wrong?

```              {
                    "ServiceType": "LockMechanism",
                    "ServiceName": "Tür Wohnzimmer",
                    "Characteristics": [
                        {
                            "Type": "LockCurrentState",
                            "Listen": [
                                "3/1/4"
                            ]
                        },
                        {
                            "Type": "LockTargetState",
                            "Listen": [
                                "3/1/4"
                            ]
                        }
                    ]
                },
```
and this

```
                {
                    "ServiceType": "LockMechanism",
                    "ServiceName": "Tür Wohnzimmer",
                    "Characteristics": [
                        {
                            "Type": "LockCurrentState",
                            "Listen": [
                                "3/1/4"
                            ],
                            "Reverse": true
                        },
                        {
                            "Type": "LockTargetState",
                            "Listen": [
                                "3/1/4"
                            ],
                            "Reverse": true
                        }
                    ]
                },
```

The Lock did not change its status.

**Comment by snowdd1** [comment]
Have to look up the characteristics. *Reverse* does **only** work with Boolean and Percentage types. First guess is that **LockTargetState** is an integer type with discrete values for states.

**Comment by snowdd1** [comment]
As I assumed, `LockCurrentState`  
https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L900   
is a UINT8 with values 0,1,2,3  

`LockTargetState` 
https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L972  
is a UINT8 with values 0 or 1  

So no Boolean value, even if it looks as if it was.

**Comment by snowdd1** [comment]
And Christof, could you read #61 for pasting code samples here? Thanks

**Comment by snowdd1** [comment]
If you need other values than the ones defined by homekit, you need to write another add-in. Like I needed for my ContactSensor, because the characteristic is a UINT8, too.

**Comment by giase82** [comment]
Ah makes sense! I was thinking the "old stuff" was working as before still... So in the time before addins, which code did the mapping? (I am asking as I would probably copy this one)

**Comment by snowdd1** [comment]
I recommend using [ContactSensor add-in](https://github.com/snowdd1/homebridge-knx/blob/master/lib/addins/ContactSensor.js#L29) as an example, because the old code worked completely different - and [I forced it to be Boolean in 0.2](https://github.com/snowdd1/homebridge-knx/blob/v0.2.8/index.js#L1031).

**Comment by giase82** [comment]
Ok, agree. We can close this then.
