### ISSUE TITLE
Can't add Homebridge

### ISSUE THREAD

**Issue by gjniewenhuijse** [snowdd1/homebridge-knx#66]
I had a working homebridge yesterday. (latest release for homebridge and homebridge-knx).

After shutdown my pi this night, my homebridge isn't found after reboot this morning.

So i shutdown the homebridge service
deleted the persist and cachedAccessories data
Start the homebridge again

The Accessory 'Homebridge" shows up ok, when i click it i get the warning message "This accessory is not certified and may not work reliably with HomeKit" selected add anyway ... and manually entered the 8 digit code which eventually results in the message "Couldn't add Homebridge / Home couldn't connect to this accessory"

Whats wrong? i get no errors in my log and the service is up.

**Comment by gjniewenhuijse** [comment]
Aiii,

I had a Characteristic.CurrentHeatingCoolingState with state 3 and thats not correct:
// The value property of CurrentHeatingCoolingState must be one of the following:
Characteristic.CurrentHeatingCoolingState.OFF = 0;
Characteristic.CurrentHeatingCoolingState.HEAT = 1;
Characteristic.CurrentHeatingCoolingState.COOL = 2;

So its solved.

**Comment by snowdd1** [comment]
Hi Geert-Jan, it was my intention to avoid sending illegal responses to HomeKit. There even is a function in the code that should block responses for characteristics that have a given list of allowed values. That somehow failed here, so I am opening this again, until I found  the mistake in the code.

**Comment by snowdd1** [comment]
Might be around that line: https://github.com/snowdd1/homebridge-knx/blob/master/lib/knxaccess.js#L280  
(For my own convenience)
