### ISSUE TITLE
Error trying to use add-in WindowCoveringTilt

### ISSUE THREAD

**Issue by zork17** [snowdd1/homebridge-knx#68]
I am new to all of this (homebridge, github...)
I have homebridge and knx working with all the lights in my house and I'm trying to make it work with the blinds that can go up and down and also tilt.

When using a WindowCoveringTilt like this in my knx_config.json:
"ServiceType": "WindowCovering", 
"Handler": "WindowCoveringTilt", 
"ServiceName": "kitchen", 
"Characteristics": [ 
...

I get the following error: 
Error: Cannot find module './addins/WindowCoveringTilt.js'

I installed homebridge-knx 0.3.2
On github I can see the file WindowCoveringTilt.js on the master branch and not on 0.3.2 tag. Is it normal?
What can I do to install WindowCoveringTilt?

**Comment by snowdd1** [comment]
Sorry it's not yet part of the npm package. I need to create a new release to publish it to npm. Maybe I can do that this evening or tomorrow.

**Comment by zork17** [comment]
thanks

**Comment by snowdd1** [comment]
Just published it.
