### ISSUE TITLE
need help with 32x32 rgb-led matrix using hat+rtc & rp3

### ISSUE THREAD

**Issue by dlorfel** [snowdd1/homebridge-knx#70]
I put this question(s) on two sites but so far have not gotten any help.  maybe this is the one.
- I was able to set up all the hardware 
- I downloaded the software from the github.com/hzeller/rpi-rgb-led-matrix/archive/master.zip site.
- the only thing I was able to get to run  after trying different options was : 
   - sudo /home/pi/rpi-rgb-led-matrix-master/minimal-example
   -  it is an excutable,  not sure where the source code is and what language it is but I assume it     is c++, so it appears the 32x32 rgb led matrix works.
- I tried running some python programs from the hzeller site and got errors like the below example:
(Traceback (most recent call last):
  File "/home/pi/rpi-rgb-led-matrix-master/ada-matrix.py", line 7, in <module>
    from rgbmatrix import Adafruit_RGBmatrix
ImportError: No module named rgbmatrix)

- sometimes the reason was that the missing module was not in the folder so i copied the module to the folder and that error went away.
- this above message (No module named rgbmatrix)) could not get it to go away even when I put a module by that name in the folder

                                            NOW SOME QUESTIONS
- Can I write code for the 32x32 hardware in Python
- where do I find the missing modules
- if the 32x32 rgb led hardware using rp3 can be used with python, is there a simple python program I can run and than modify
- are there any good sites I can go to that will help me or
- have you got any good suggestions why using the hzeller download pyhon examples do not work.and how I might be able to make them work.
- any help what so ever will be greatly appreciated.
- the sites I already put this issue on was the adafruit site and the raspberry pi official site on their forums.
- if you do not have a good answer, than can you suggest some other forums or sites I can possibly get help from

Because I never used this site before and not even sure how to find out where responses are, if someone does have some information for me,  can you email me the link the answer will be on or emal me the answer at dlorfel@yahoo.com

Thank You very much for your help
dlorfel
and happy new year

**Comment by snowdd1** [comment]
Is this related to Apple HomeKit and home bridge KNX in any way?

**Comment by snowdd1** [comment]
seems to be unrelated to KNX.
