### ISSUE TITLE
Sync issue

### ISSUE THREAD

**Issue by vddgil** [snowdd1/homebridge-knx#71]
Hello,

I'm configuring homebridge knx at home. I can switch on and off the light without problem from the apple home app. But, when I use a physical switch to switch on/off the light, the status in the apple home app doesn't update.

Here is my knk_config.json
```json
{
    "knxd_ip": "192.168.1.55",
    "knxd_port": 6720,
    "AllowWebserver": true,
    "AllowKillHomebridge": false,
    "Devices": [
        {
            "DeviceName": "Plafonnier",
            "Services": [
                {
                    "ServiceType": "Lightbulb",
                    "ServiceName": "Plafonnier bureau",
                    "Characteristics": [
                        {
                            "Type": "On",
                            "Set": [
                                "24/4/8"
                            ],
                            "Listen": [
                                "24/4/7"
                            ]
                        }
                    ],
                    "KNXReadRequests": [
                        "24/4/8"
                    ],
                    "subtype": "SUB_08ef28ba-1f3b-4cde-a735-297e49e0f8ef"
                }
            ],
            "UUID": "8cf72c4c-feb9-4cba-99f2-1152265cf532"
        }
    ],
    "GroupAddresses": []
}
```

I monitored my knxd process:

When I switch on the light with the home app:
```
LPDU: BC 00 00 C4 08 F1 00 81 FF :L_Data low from 0.0.0 to 24/4/8 hops: 07 T_DATA_XXX_REQ A_GroupValue_Write (small) 01
LPDU: BC 00 01 C4 08 E1 00 81 EE :L_Data low from 0.0.1 to 24/4/8 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 01
LPDU: BC 02 0D C4 07 E1 00 81 EF :L_Data low from 0.2.13 to 24/4/7 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 01
```

When I switch off the light with the home app:
```
LPDU: BC 00 00 C4 08 F1 00 80 FE :L_Data low from 0.0.0 to 24/4/8 hops: 07 T_DATA_XXX_REQ A_GroupValue_Write (small) 00
LPDU: BC 00 01 C4 08 E1 00 80 EF :L_Data low from 0.0.1 to 24/4/8 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 00
LPDU: BC 02 0D C4 07 E1 00 80 EE :L_Data low from 0.2.13 to 24/4/7 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 00
```

When I switch on the light with my physical switch:
```
LPDU: BC 02 05 C4 08 E1 00 81 E8 :L_Data low from 0.2.5 to 24/4/8 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 01
LPDU: BC 02 0D C4 07 E1 00 81 EF :L_Data low from 0.2.13 to 24/4/7 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 01
```
When I switch off the light with my physical switch:
```
LPDU: BC 02 05 C4 08 E1 00 80 E9 :L_Data low from 0.2.5 to 24/4/8 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 00
LPDU: BC 02 0D C4 07 E1 00 80 EE :L_Data low from 0.2.13 to 24/4/7 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 00
```

It seems that everything is working fine with KNXD as I can see every action I take with my physical switch or with the apple home app.

The only problem is when I use my physical switch, the status of the light doesn't update in the apple home app.

Here where a get my knx addresses:
![KNX Addresses](https://cloud.githubusercontent.com/assets/81749/21612429/6f187176-d1d1-11e6-91e6-7e207e3a4ab4.png)

Thanks in advance,

Gil

**Comment by snowdd1** [comment]
Hi Gil,
just being back from vacation. I think it related to your other issue regarding the address range. I used an existing nodejs package to communicate with knxd/eibd, and this package does not support 32-bit addresses - at least not completely, I seems to be able to send valid datagrams but cannot read the address of an incoming 32-bit address datagram. So your light will not be updated.  
Since I have a lot of legacy KNX devices that do not support that either I had not seen this upfront.  

I have just openend an issue for that at `node-eibd` [Issue 40](https://github.com/andreek/node-eibd/issues/40)

**Comment by snowdd1** [comment]
Same root cause as #72
