### ISSUE TITLE
error after updating KNXD

### ISSUE THREAD

**Issue by gjniewenhuijse** [snowdd1/homebridge-knx#80]
After updating my KNXD to version 0.13 it stops working.

In my error log i see:
[Fri Feb 10 2017 10:12:07 GMT+0100 (CET)] [homebridge-knx.KNX] [ERROR] knxwrite:openTGroup: Error: request invalid

**Comment by timurapv** [comment]
The same error on same version :(

**Comment by snowdd1** [comment]
I just tested with  
- branch **stable** = branch v0.12: reads version number 0.12.12: working 
- branch **master**: reads version number 0.13.0:dd46a14: working  

You might have done some harm to your installation?!  
**In any case, use a** *stable* **branch of knxd for any production like environment!**

**Comment by snowdd1** [comment]
Not that confident any more, homebridge died this morning with a strange connection message. Have to investigate further.

**Comment by snowdd1** [comment]
Seemed to be a coincidence. I upgraded too many things at once, and fried my SD CARD while doing so.  
Now switched the SD card, installed a new Raspbian, moved the root directory to an NFS share (to not fry the card again with a lot of logging) installed all again and - voila - it's stable with the **stable** branch of knxd again.  

Now it runs with 
```
pi@knxd2-raspberry:~ $ npm list
/home/pi
├─┬ homebridge@0.4.16
│ ├─┬ chalk@1.1.3
│ │ ├── ansi-styles@2.2.1
│ │ ├── escape-string-regexp@1.0.5
│ │ ├─┬ has-ansi@2.0.0
│ │ │ └── ansi-regex@2.1.1
│ │ ├── strip-ansi@3.0.1
│ │ └── supports-color@2.0.0
│ ├─┬ commander@2.8.1
│ │ └── graceful-readlink@1.0.1
│ ├─┬ hap-nodejs@0.4.20
│ │ ├── buffer-shims@1.0.0
│ │ ├─┬ curve25519-n@1.1.0
│ │ │ ├── bindings@1.2.1
│ │ │ └── nan@2.5.1
│ │ ├─┬ debug@2.6.1
│ │ │ └── ms@0.7.2
│ │ ├── ed25519@0.0.4
│ │ ├── fast-srp-hap@1.0.0
│ │ ├── ip@1.1.4
│ │ └─┬ mdns@2.3.3
│ │   └── nan@2.3.5
│ ├─┬ node-persist@0.0.8
│ │ ├── mkdirp@0.3.5
│ │ └── q@1.1.2
│ └── semver@5.0.3
└─┬ homebridge-knx@0.3.5
  ├─┬ debug@2.6.1
  │ └── ms@0.7.2
  └── eibd@0.3.7

pi@knxd2-raspberry:~ $ knxd -V
knxd 0.12.12
```

On my production I am not going to use **master** (unstable). I am not sure what killed my raspberry, probably the kernel update, however, it ran for some time and started getting unstable after an hour or so, and after a reboot today didn't get up at all. Had to re-image the whole card, so something with the kernel and kernel modules seemed to be broken.

**Comment by gjniewenhuijse** [comment]
I installed knxd 0.10.14 version back on my pi and its works again. 

I think my os is to old:

No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.11 (wheezy)
Release:        7.11
Codename:       wheezy

**Comment by snowdd1** [comment]
Jessie is minimum if you are not up to tweak it, see issues at knxd.
