### ISSUE TITLE
How to upgrade?

### ISSUE THREAD

**Issue by hyperbart** [snowdd1/homebridge-knx#87]
@snowdd1 could you add something to the readme on how to upgrade the homebridge-knx?

I have a V0.3 now but it's the one without your fix for the dimming-bug. Would like to upgrade without reinstalling completely ;)

**Comment by snowdd1** [comment]
Installing homebridge-KNX over an existing installation does no harm. It definitively does not overwrite any configuration files.  
Depending whether you have installed it globally or not just issue one of the commands in #82
