### ISSUE TITLE
Zuordnung ETS zu HomeKit 

### ISSUE THREAD

**Issue by petkoe** [snowdd1/homebridge-knx#9]
Ich versuche gerade mal eine Zuordnung aus der Konfiguration HomeKit zu den Elementen aus meiner ETS zu machen: 

| ETS/KNX | Geraet | Wert | Homekit | Spec | Typ |
| --- | --- | --- | --- | --- | --- |
| Schaltaktor | Rollladen | Langzeitbetrieb | WindowCovering |  |  |
|  |  | Kurzzeitbetrieb |  |  |  |
|  |  | Rückmeldung Rolladenposition |  | Target | Listen |
|  |  | Rückmeldung Antriebsbewegung |  |  |  |
|  |  | Position Rolladen/Markise |  | Target | Set |
| Schaltaktor | Steckdose | Schalten | Outlet / Switch ??? | On | Set |
|  |  | Rückmeldung Schalten |  |  |  |
| Dimmaktor | Lampe | Schalten | Lightbulb | On | Set |
|  |  | Dimmen |  | Brightness | Set |
|  |  | Helligkeitswert |  |  |  |
|  |  | Rückmeldung Schalten |  | On | Listen |
|  |  | Rückmeldung Helligkeitswert |  | Brightness | Listen |
|  |  |  |  |  |  |
|  |  |  |  |  |  |
|  |  | Ist-Temperatur | TemperatureSensor | CurrentTemperature | Listen |
|  |  | Soll-Temperatur |  |  |  |

Das ganze erstmal auf Deutsch, da meine ETS auf Deutsch ist, aber ich kann auch versuchen daraus eine englische Fassung zu machen, falls das interessant ist und das dann ins WIKI einzutragen.

Peter

**Comment by snowdd1** [comment]
Hallo Peter,
Finde ich eine gute Idee.
Grundsätzlich sind die "Listen" Attribute eher mit den Rückmeldungen zu verbinden, wenn es welche gibt, sowie die "Current" characteristica eher Rückmeldungen als Schaltgruppenadressen.

Beispiel Rolladen: Die Rückmeldung der Position sollte auf "CurrentPosition" "Listen" gesetzt werden, die "Position Rolladen" (mit dem man die Anfahrt steuern kann) auf "TargetPostion" "Set" gesetzt werden.

Derzeit ist es so programmiert, dass auf den bei "Set" angegebenen Adressen grundsätzlich auch mitgehört wird. Wenn es kein "Set" gibt, wird über homebridge nicht auf den Bus geschrieben, sindern höchstens mit einem Read-Request angefragt und ansonsten gelauscht.

**Dimmen** ist normalerweise ein 4-bit richtung/start/stop-Kommando, das keinem konkreten Wert entspricht, dies auf keinen Fall zuordnen, nur "Helligkeit" =Target und "Rückmeldung Helligkeitswert" = Current verwenden!
Gruß
Raoul

**Comment by snowdd1** [comment]
BTW Outlet und Switch sind sich sehr ähnlich. Apple dachte sich aber, dass es für Steckdosen cool wäre, wenn sie zurückmelden ob die Steckdose gerade mit einem Verbraucher verbunden ist. Meine Steckdosen sind an einem normalen Schaltaktor, daher kann ich sie wahlweise betreiben.
Es könnte natürlich sein, dass Siri auf "Schalte alle Steckdosen aus" richtig reagiert, wenn sie auch als Steckdosen (Outlet) konfiguriert sind. Habe ich noch nicht ausprobiert, und habe ich auch keinen sinnvollen Anwendungsfall für, da an den Steckdosen ja meistens bestimmte Geräte hängen, die man schalten möchte...

**Comment by petkoe** [comment]
Hallo Raoul,

so ich habe es jetzt mal umgesetzt und auch in englisch ins wiki. Das mit dem Dimmen ist richtig (auch wenn ich es immer verwechsle :-( ) 

Übrigens: Ich habe das ganze jetzt noch in der alten Fassung auf einem RPI und in der neuen Version als plugin unter macosx laufen. Falls es etwas zum Testen gibt bin ich gerne bereit auch auf konkretes hin zu testen. 

Viele Grüße,

Peter
