### ISSUE TITLE
buffer.js:  Error   "value" argument must not be a number

### ISSUE THREAD

**Issue by Demonderik** [snowdd1/homebridge-knx#90]
Hi snowdd1, 

After updating homebridge to version v0.4.1, I have broken homebridge-knx.
It always throws error ""value" argument must not be a number" in buffer.js - parser call of the eibd module during (any?) attempt to read the telegram from knx. (knxd runs on another docker image).

Do you have any idea how to solve it?

homebridge v0.4.17
homebridge-knx v0.3.10
node v6.10.0

[37m[4/13/2017, 1:32:41 PM][39m [36m[Volume][39m Get receiver volume 47 
stdout
13:32:41
[37m[4/13/2017, 1:32:41 PM][39m [36m[Marantz][39m current power state is: OFF
stdout
13:33:09
buffer.js:93
stdout
13:33:09
    throw new TypeError('"value" argument must not be a number');
stdout
13:33:09
    ^
stdout
13:33:09
stdout
13:33:09
TypeError: "value" argument must not be a number
stdout
13:33:09
    at Function.Buffer.from (buffer.js:93:11)
stdout
13:33:09
    at Parser.parseTelegram (/usr/lib/node_modules/homebridge-knx/node_modules/eibd/lib/parser.js:84:43)
stdout
13:33:09
    at Parser.onData (/usr/lib/node_modules/homebridge-knx/node_modules/eibd/lib/parser.js:150:12)
stdout
13:33:09
    at Socket.<anonymous> (/usr/lib/node_modules/homebridge-knx/node_modules/eibd/lib/parser.js:36:10)
stdout
13:33:09
    at emitOne (events.js:96:13)
stdout
13:33:09
    at Socket.emit (events.js:188:7)
stdout
13:33:09
    at readableAddChunk (_stream_readable.js:176:18)
stdout
13:33:09
    at Socket.Readable.push (_stream_readable.js:134:10)
stdout
13:33:09
    at TCP.onread (net.js:548:20)

**Comment by snowdd1** [comment]
Hi @Demonderik ,
yes, I prepared a faulty pull request for the `eibd` package, which does not work with node 6.4 and above as far as I learned. I already prepared a corrected PR, and hope that André, the maintainer of `eibd` package, will accept the [PR](https://github.com/andreek/node-eibd/pull/49) soon. 

For the time being, you can install eibd version 0.3.7 whicha hadn't had the error.

**Comment by Demonderik** [comment]
Hi Raoul,
thank you for quick response!

I tried to install eibd@0.3.7
and (or) node@6.3.0
NO success. The same error at the same place.

my install.sh:
#!/bin/bash
node -v
npm cache clean -f
npm install -g n
n 6.3.0
#n 6.10.0
node -v

npm install -g homebridge-knx
npm install -g homebridge-harmonyhub
npm install -g homebridge-denon
npm install -g homebridge-marantz-volume
npm install -g eibd@0.3.7

**Comment by snowdd1** [comment]
there is a new version 0.3.9 that should be fixed for use with node > 6.2

**Comment by Demonderik** [comment]
Hooray! Hooray!  #49 is fixed my problem! With eibd@03.9 everything works now!

Raoul, Andree, thanks for quick fix!
Great job!
