### ISSUE TITLE
cache problem

### ISSUE THREAD

**Issue by deejonz** [snowdd1/homebridge-knx#94]
Hello, 
every time that I restart homebridge I get all my devices duplicated on the homekit app on the iphone. Is that normal? 
With the previous version I've never got this issue.
I'm using the latest version of nodejs, npm, homebridge and homebridge-knx.

**Comment by snowdd1** [comment]
Only if you apply a new version of the knx_config.json - the plugin generated random codes for each new accessory/device/service and tries to match them to those found in homebridge's cache.  

Do you have switched to using a ramdisk to protect your SD card on raspberry recently?

If neither applies to you, could you paste a start log of homebridge with DEBUG=* for debugging?

**Comment by deejonz** [comment]
I tried a few times to restart homebridge and I cannot reproduce the issue anymore (which is good). If I'll get this again I'll continue on this conversation - thank you.

**Comment by snowdd1** [comment]
closing for now, please re-open if required!
