### ISSUE TITLE
Implementation of TemperatureSensor

### ISSUE THREAD

**Issue by ctschach** [snowdd1/homebridge-knx#96]
I'm pretty new to all this, so it might be a dumb question: I know that there is a service type called "TemperatureSensor". How do I set this up with homebridge-knx?

Any configurations samples?

**Comment by ctschach** [comment]
Okay, I figured it out...but...

```
                {
                    "ServiceType": "TemperatureSensor",
                    "ServiceName": "Temperatur",
                    "Characteristics": [
                        {
                            "Type": "CurrentTemperature",
                            "Listen": [
                                "5/1/15"
                            ],
                            "DPT": "DPT9"
                        }
                    ]
                }
```

But...I was hoping that I could use Elgato Eve's app to display a nice little graph of my temperature....but unforunately this does not work.

But I guess it's not an issue of homebridge-knx and more a issue of homebridge in general.

**Comment by snowdd1** [comment]
Elgato uses an TLV data series for the graph from its own devices. Never played with that.

**Comment by ctschach** [comment]
Basierend hierauf müsste man ja eigentlich in der Lage sein, die Tempratur-History einzubauen:

https://github.com/simont77/fakegato-history

**Comment by snowdd1** [comment]
Klingt cool. Habe aber gerade wenig Zeit - neuer Job...

**Comment by Mr-S-D** [comment]
Is there any way to see/add decimals? If the temperature outside is 23.5 it shows as 24, but if I would like it to show 23.5, could that be done? The same goes for adjusting thermostats, can steps on the set value be 23.5 instead of 23 or 24? So increase by 0.5 instead of 1 degrees?

**Comment by snowdd1** [comment]
That's a question of decimals in the front end. Home app is very basic, have you tried other apps like Elgato EVE?
