### ISSUE TITLE
How to program WindowCovering shutters

### ISSUE THREAD

**Issue by migabc** [snowdd1/homebridge-knx#98]
Hi,

Can someone give me some insight on how to program my shutters?

My KNX project has these GAs:

      <GroupAddress Name="Kitchen Shutter - M" Address="1/2/21" />      #Up/Down
      <GroupAddress Name="Kitchen Shutter - ST" Address="1/2/22" />    #Step
      <GroupAddress Name="Kitchen Shutter - V" Address="1/2/23" />      #0% (Open); 100% (closed)
      <GroupAddress Name="Kitchen Shutter - VFB" Address="1/2/24" />  #Value % Feedback
      <GroupAddress Name="Kitchen Shutter - SLAT - V" Address="1/2/25" /> #0% (Slat open); 100% (slat closed)
      <GroupAddress Name="Kitchen Shutter - SLAT - VFB" Address="1/2/26" /> #Horizontal slat %feedback

Thanks,
Miguel

**Comment by snowdd1** [comment]
Hi Miguel, does that https://github.com/snowdd1/homebridge-knx/blob/master/lib/addins/WindowCoveringTilt.js#L176-L241 help you?

**Comment by migabc** [comment]
Nice!! :-)
That handler works perfectly.
Thanks a lot

**Comment by OliAhn** [comment]
> Hi,
> 
> Can someone give me some insight on how to program my shutters?
> 
> My KNX project has these GAs:
> 
> ```
>   <GroupAddress Name="Kitchen Shutter - M" Address="1/2/21" />      #Up/Down
>   <GroupAddress Name="Kitchen Shutter - ST" Address="1/2/22" />    #Step
>   <GroupAddress Name="Kitchen Shutter - V" Address="1/2/23" />      #0% (Open); 100% (closed)
>   <GroupAddress Name="Kitchen Shutter - VFB" Address="1/2/24" />  #Value % Feedback
>   <GroupAddress Name="Kitchen Shutter - SLAT - V" Address="1/2/25" /> #0% (Slat open); 100% (slat closed)
>   <GroupAddress Name="Kitchen Shutter - SLAT - VFB" Address="1/2/26" /> #Horizontal slat %feedback
> ```
> Thanks,
> Miguel

Hi Miguel,

I do have the same problem. Any chance, that you could post me the config for the shutters? Regards, Oliver
